### ISSUE TITLE
[10.0] currency_rate_update: Tests are failing

### ISSUE THREAD

**Issue by rousseldenis** [OCA/account-financial-tools#1002]
I'm not in favor of tests with real url as they depends on external service reliability.

It can causes troubles on the repository for PR's with unrelevant errors: the module code is not the culprit, the service is.

As I know some people are against mocking url requests, but IMHO it ensures module test isolation. Testing without mock can cause unwanted errors on PR's or even in main branches. 

See https://travis-ci.org/github/OCA/account-financial-tools/jobs/690972159#L1633 and the corresponding service description : https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=1

As it allows one request per 5 minutes, we are limited in one test for the whole repository!!!

@jcdrubay @alexis-via @sbidoul

**Comment by pedrobaeza** [comment]
First of all, I think that provider should go to OCA/l10n-vietnam. About testing the real thing, you know my preference :wink:

**Comment by rousseldenis** [comment]
> As it allows one request per 5 minutes, we are limited in one test for the whole repository!!!

Yes, and that argument is in favor of mine. :smiley: That would be the same in vietnam repository

**Comment by rousseldenis** [comment]
> > As it allows one request per 5 minutes, we are limited in one test for the whole repository!!!
> 
> Yes, and that argument is in favor of mine.  That would be the same in vietnam repository

And people seeing errors on PR's would never review it nor PR's makers even try to fix it. 'the snake bites its tail'...

**Comment by jcdrubay** [comment]
Hi,
the URL has changed indeed.
Let me know if you wish me to take some actions.
Maybe [1] you can remove the module causing the issue from this repo, and eventually [2] we could add it back in the repository OCA/l10n-vietnam.
I can take care of [2] if you want.
Regards,
Jean-Charles

**Comment by rousseldenis** [comment]
> Hi,
> the URL has changed indeed.
> Let me know if you wish me to take some actions.
> Maybe [1] you can remove the module causing the issue from this repo, and eventually [2] we could add it back in the repository OCA/l10n-vietnam.
> I can take care of [2] if you want.
> Regards,
> Jean-Charles

Ok, I will remove service in module. Could you at least do an issue on vietnam repo?

**Comment by jcdrubay** [comment]
Actually, the service is already extracted since v11: https://github.com/OCA/l10n-vietnam/tree/11.0/currency_rate_update_VN_VCB

So if people want to have in v10, they can downport the module from v11 to v10. Or I should create 2 issues:

- update url in v11
- downport to v10

I suggest you just remove from v10 of this repo.

Today, we have no-one really contributing in the l10n-vietnam repo.
Hopefully it will change in the future.
