### ISSUE TITLE
account_asset_management: Add chatter entry in invoice for generated asset

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#1006]
It would be good to have that chatter entry with the link to the asset as we see in invoices created from sales orders for example.

**Comment by HaraldPanten** [comment]
It would be an interesting feature. I agree with the [IMP]

Will you purpose a PR? Which Odoo version?

THX!

**Comment by pedrobaeza** [comment]
I haven't planned it yet. You can do the PR if you want/have time.

**Comment by HaraldPanten** [comment]
Hi Pedro,

Do you have any special requirement for this IMP that should be taken in consideration? Otherwise, we'll make our own purpose.

**Comment by pedrobaeza** [comment]
No, follow the examples in core where you have a note entry with the link to the created object to click in it.
