### ISSUE TITLE
[11.0 account_lock_to_date ] You cannot lock a period that is not finished yet

### ISSUE THREAD

**Issue by desdelinux** [OCA/account-financial-tools#1009]
On any date when trying to block, the following error appears

Next error message

You cannot lock a period that is not finished yet. Please make sure that the lock date for advisors is not set after the last day of the previous month.
Can be validated in the next runbot http://3424915-11-0-b3ff0f.runbot3.odoo-community.org/

![image](https://user-images.githubusercontent.com/50924836/84212629-fe2cad80-aa83-11ea-8b83-fa8a110c5be6.png)

![image](https://user-images.githubusercontent.com/50924836/84212725-3b913b00-aa84-11ea-9f9b-d9e419ca8bed.png)

![image](https://user-images.githubusercontent.com/50924836/84212736-45b33980-aa84-11ea-95ed-98dd95ad4676.png)

**Comment by cubells** [comment]
I confirm this issue doing this module unusable.

I try to do a patch for this bug but I'd have to rewrite all tests.

@JordiBForgeFlow can you confirm this bug or try to explain me how to this module works?

And to make matters worst, spanish translation I think is not correct:

> No se puede bloquear un periodo que no ha transcurrido todavía. Por favor, asegúrate de que la fecha bloqueada **no es anterior** al último día del mes anterior. 

When in english is this: 

> You cannot lock a period that is not finished yet. Please make sure that the lock date for advisors **is not set after** the last day of the previous month.

And the code is not obvious. Comment said **next month**:

https://github.com/OCA/account-financial-tools/blob/11.0/account_lock_to_date/models/res_company.py#L82

And validationerror said **previous month**:

https://github.com/OCA/account-financial-tools/blob/11.0/account_lock_to_date/models/res_company.py#L87

@JordiBForgeFlow can you help me?

**Comment by AaronHForgeFlow** [comment]
That module prevents to create journal entries too far in the future. For example, I don't want users to post a journal entry for 2021. Then I set the lock date on 01/01/2021

**Comment by enricostano** [comment]
@AaronHForgeFlow @cubells which module would you use to lock past fiscal periods instead? Thanks!

**Comment by cubells** [comment]
@enricostano https://github.com/OCA/account-financial-tools/tree/13.0/account_lock_date_update
