### ISSUE TITLE
account_asset_management[IMP][RFO] asset entries creation using scheduled action

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/account-financial-tools#1011]
Hi,

I was wondering if it would make sense to include a scheduled action where the asset entries would be created periodically. Quite similar as account_asset module does in Odoo EE.

I'm talking about V12, but probably it could be backported/forwardported to other versions.

What do you think @pedrobaeza @JordiBForgeFlow ?

THX

**Comment by pedrobaeza** [comment]
I haven't missed it, as all my customers wants to do it manually through the menu entry.

**Comment by HaraldPanten** [comment]
> I haven't missed it, as all my customers wants to do it manually through the menu entry.

What about if customer has lots of assets and assets entries? Is it OK to do it manually/massively several times for each period?

THX

**Comment by pedrobaeza** [comment]
I don't get you... Do you mean that several users do it simultaneously?

**Comment by HaraldPanten** [comment]
No, let me explain:

You can create the asset entries by two ways:

**1- One by one, by line, for each asset:**

<img width="1427" alt="Captura de pantalla 2020-07-01 a las 12 32 53" src="https://user-images.githubusercontent.com/32449357/86234650-8e4ba780-bb97-11ea-9e98-f02d912944c4.png">

**2- Massively for a limit date, using "Compute assets" option:** 

<img width="1221" alt="Captura de pantalla 2020-07-01 a las 12 33 09" src="https://user-images.githubusercontent.com/32449357/86234664-9277c500-bb97-11ea-8f8a-4736efb984b3.png">


Imagine that you have a client who needs to create several assets, several times a month. He/she's actually manually using "create assets" option, but it would be better for him/her to let the program do it automatically with a scheduled action (once a week, once a month...) as EE does.

As they have to do this process lots of times, it's not a good UX for them to do it manually (even with "create assets" option).

THX

**Comment by pedrobaeza** [comment]
I think you have switch the term "Compute Assets" with "create assets", but I get your idea. I honestly think that the use case you are talking about is a bad user behavior, as the asset depreciation entries are always created for past times, so if you have the need of creating several forgotten assets, create them, and then run once the "Compute Assets" menu. If you want to "see the progress", you will need to run manually the wizard several times. Anyway, it's only 2 clicks, so it's not a great overhead.

**Comment by HaraldPanten** [comment]
Hi Pedro,

The main objective of this IMP would be to let the cron (scheduled action) create the entries instead of a "needed user action".

As you have the depreciation dates in the assets, the cron would automatically create the entries once the date was something like this pseudocode:

 `"depreciation date line"<="Today"`

It would be 100% compatible with the actual features and we will include https://github.com/OCA/account-financial-tools/issues/1006 in our IMP 😉

**Comment by pedrobaeza** [comment]
OK, I'm not against it, but it should be disabled by default.

**Comment by HaraldPanten** [comment]
> OK, I'm not against it, but it should be disabled by default.

I agree

**Comment by HaraldPanten** [comment]
Closing, as https://github.com/OCA/account-financial-tools/pull/1016 has been merged
