### ISSUE TITLE
[12.0/13.0] account_asset_management: Depreciation lines as init entries for asset with prorata

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#1012]
With the following use case:

- Advisor accounting lock date (the bad called technical field `fiscalyear_lock_date`): 2020-05-31
- Create asset with prorata with start date: 2020-06-01 (or any later date)
- Compute depreciations

**Result**: all the depreciation lines for 2020 appears in black as init entries.

**Expected**: all the depreciation lines for 2020 appears normally to generate journal entries.

I don't think that date should be used to block the entire year, or at least not with prorata. I think the same will happen without prorata, as the problem comes from the concept given to that field.

**Possible solution**: Take `fiscalyear_lock_date`, and compute the immediately previous end of FY date as limiting date.

**Comment by pedrobaeza** [comment]
@luc-demeyer what do you think about this? I don't know yet the code enough for knowing if doing a direct change of this date in the table computation will have other side effects.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
I think your suggestion makes a sense and I don't expect side effects.
Another option could be that we add an 'accounting_entry_start_date' field and hence don't use the confusing fiscalyear_lock_date field at all.

**Comment by pedrobaeza** [comment]
Yes, `accounting_entry_start_date` can be the way to go, but taking it also as an absolute value, not the whole fiscal year including that date.

**Comment by luc-demeyer** [comment]
@pedrobaeza 
indeed as absolute value

**Comment by bunhin** [comment]
I believe the init entry (block) a way better when it is configurable, beside auto block until last month of  previous fiscal year as the default. This way when we entry a lot of assets in the midle of fiscal year, we do not need to manualy open in form view just to check as init entry (in current state, when we are in list view is not allowed to check that init box)

related to this, As other enhancement options, may be a good alternative to have compute depreciation board for all asset in draft state therefore we do not need to click the button one by one of each asset just to have the depreciation lines to export and set init entry as true then import back.   I try to call the method (compute depreciation board) from ir cron, but it seem not suitable for execution from ir cron.  will try to wrap the method so callable from ir cron (manual one call only).

**Comment by pedrobaeza** [comment]
Closing as fixed.
