### ISSUE TITLE
Account_check_deposit

### ISSUE THREAD

**Issue by mm82299** [OCA/account-financial-tools#1019]
Dear All,
I have installed the module **account_check_deposit** and configured the journal check received and tried to deposit a check to the bank but couldn't found the check deposit menu under invoicing--->Accounting --->check Deposit.

Can someone help please ?

**Comment by NCS-75** [comment]
Hi,
Please, rename explicitly your request if you expect to receive an answer. 

As it for exemple : 

- [13] [Help] (Configuration) "Account_check_deposit" Don't see menu entry

Preamble 
You really have to you follow all the explainations all along the "README.rst"  : https://github.com/OCA/account-financial-tools/tree/13.0/account_check_deposit#id1
By the way, please always try "runbot environnement" from the link, it helps !

Also,you need to check the user environnement rights setting.

In case of confusion; then always explain, describe,  following elements ..
- Context : version of odoo, version of module, eventualy, the module tier environnement, etc..
- Steps to reproduce , and so on..

This could  help the OCA community contributors, to eventualy, improve the "Readme file ", in case..

And please, document the request by any screenshot of what you're facing (a picture is worth a thousand words)

Thank you for your understanding, each one will save time

For your problem, i guess you  probably didn't not set  - [x ] "Show Full Accounting Features",  in Setting/Users & Companies/Users

**Comment by pedrobaeza** [comment]
Closing meanwhile further explanation is done. @NCS-75 thanks for the detailed and kind answer.
