### ISSUE TITLE
[13.0][RFO] account_asset_management small translation FIX

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/account-financial-tools#1029]
Hi @pedrobaeza 

I've realized that there's a translation issue in account_asset_management due it's translation to Spanish.

As you can see in my screenshots, there's no difference between **Asset Goup(s)** vs **Asset Profile(s)**. That can cause confusion to users.

My question is: Can I do this small changes by using a PR here? Or should I manage this situation using Weblate?

Regards,

![Captura de pantalla 2020-07-22 a las 10 01 42](https://user-images.githubusercontent.com/32449357/88151147-9a5cdf00-cc02-11ea-9d12-dea4ad7360a7.png)
![Captura de pantalla 2020-07-22 a las 10 02 09](https://user-images.githubusercontent.com/32449357/88151152-9b8e0c00-cc02-11ea-9fca-92f819d167ce.png)
![Captura de pantalla 2020-07-22 a las 9 59 23](https://user-images.githubusercontent.com/32449357/88151156-9c26a280-cc02-11ea-822c-79b4da3230c6.png)

**Comment by pedrobaeza** [comment]
In Weblate, as it's a translation thing.
