### ISSUE TITLE
[account_asset_management] [12] Setup already existing assets 

### ISSUE THREAD

**Issue by enricostano** [OCA/account-financial-tools#1031]
Hi,
I'm using modules `account_asset_management` and `l10n_es_account_asset` on a v12.

We need to setup assets that are already depreciated in previous fiscal years. For instance an asset that has been bought in 2018 and has been already depreciated every year.
Now that we're starting using Odoo for asset management we need to create the asset but we don't know how to specify that the Depreciated Value is already > 0.
As you can see in the following attachment, we can only set the Purchase Value, but not the Depreciated Value.

Any hint? Thanks!

![Screenshot_2020-07-27 New - Odoo](https://user-images.githubusercontent.com/748971/88563360-32f3c480-d032-11ea-8234-0298e97255d7.png)

**Comment by pedrobaeza** [comment]
Setup it as it's new, but with the starting date on the past, compute the depreciation board, and mark the lines that are already depreciated with the "Init" mark.

**Comment by luc-demeyer** [comment]
This goes automatically if you set the lock date, cf.
https://github.com/OCA/account-financial-tools/blob/65b6137ce075425c94953dfaee2c2708c57cd603/account_asset_management/models/account_asset.py#L990

**Comment by pedrobaeza** [comment]
About that, I have a pending issue, as that's a bad approach IMO: you use that lock date for locking periods (not fiscal years) already presented in the tax reports, but they mark entire fiscal years that way!

**Comment by luc-demeyer** [comment]
cf. my update in https://github.com/OCA/account-financial-tools/issues/1012

**Comment by pedrobaeza** [comment]
I didn't remember I already issued it! Sorry for the off-topic. As this is answered anyway, let's close it.

**Comment by enricostano** [comment]
So, we tried what @pedrobaeza suggested and it seems to be a good solution.

The only problem that we see is that when we calculate the depreciation table with **Period Length** (method_period) set to `month` or `quarter` and **Computation Method** (method) set to `linear`, the first depreciation line is higher than the others.

![Screenshot_2020-07-29 Laptop - Odoo](https://user-images.githubusercontent.com/748971/88807802-76753c80-d1b2-11ea-9183-59a11705c0e7.png)
![Screenshot_2020-07-29 Laptop - Odoo(1)](https://user-images.githubusercontent.com/748971/88807836-7b39f080-d1b2-11ea-820b-b1842032ce1d.png)

The problem with this is that if we try to modify the **Amount** of that first depreciation line accordingly to the actual amount we depreciated at that time (let's say 50,00), the **Amount Already Depreciated** of the next depreciation line is wrong (150,00 instead of 50,00).

![Screenshot_2020-07-29 Laptop - Odoo(2)](https://user-images.githubusercontent.com/748971/88808541-52662b00-d1b3-11ea-951d-aaa85cab6301.png)

Is there a way to fix this? To recalculate in some way the rest of lines for instance or to manually set those values.

Many thanks for your help!

**Comment by luc-demeyer** [comment]
I don't see the init flag on the line you changed.

**Comment by enricostano** [comment]
> I don't see the init flag on the line you changed.

@luc-demeyer yeah, sorry... I missed that in the screeshots.. but it doesn't affect the issue I'm reporting related to the Amount Already Depreciated on the next lines

**Comment by luc-demeyer** [comment]
set init flag + recompute should do the trick.

**Comment by enricostano** [comment]
Thanks, it works! :smiley: 

Out of curiosity, is there any reason why the linear method doesn't calculate the amounts evenly? I was expecting in this example:

Purchase value: 1000
Purchase date: 7 Aug 2018
Years: 5
Period length: quarter

Quarters in 2018: 2
Quarters in 2019: 4
Quarters in 2020: 4
Quarters in 2021: 4
Quarters in 2022: 4

Total quarters: 18

Each depreciation line amount should be something like 55,55 (1000 / 18). I understand that we try to avoid weird rounding, but at least the difference between amounts could be less. For instance we could have one of the following:

 - 17 lines with amount 56 euros and the last one with 48 euros
 - 17 lines with amount 55,50 euros and the last one with 56,50 euros

In any case, I'll check with accounting if this is something we can cope with or we need more help. Thanks!!!

**Comment by luc-demeyer** [comment]
the calc logic is fiscal year based.
First the FY year amount is calculated.
After that the amount is equaly split over the periods.
Rounding is done in the last period of the fiscal year.

**Comment by enricostano** [comment]
Ok, thanks for the explanation!

**Comment by bunhin** [comment]
I am sorry but can not set the init flag manually, I already in edit mode, when mouse over the init box, the forbidden sign is shown [V11], thank you to somebody can help point out what to to to be able to set init flag manually
