### ISSUE TITLE
Issue in Currency Rate Update Module[V8]

### ISSUE THREAD

**Issue by falinwa** [OCA/account-financial-tools#104]
Hi OCA,

I have migrated our database from v7 to v8,
Since V7 we have used this module(Currency Rate Update), and in V8 we used this module too.
But when I tried to configure it, we have a bug that said: "super_res is not defined", and the currency records that we want to update is not in the table, and when we want to choose it again, there's no show on it too. (In V7 we have: HKD,EURO,USD). I tried to delete this configuration and reconfigure again, but still the behavior is the same.

Can you check why?

Here is the video to explain things:
https://www.dropbox.com/s/3y66ov0tvtjkbos/curbug.avi?dl=0

**Comment by feketemihai** [comment]
Can you tell me which service are you using and please post part of the error from logfile...In essence difference between v7 and v8 is new API, supported currencies per service, restructure the module ...i think in V7 there was an extra table...currency.rate.update beside currency.rate.update.service...in V8 there is only currency.rate.update.service....

**Comment by falinwa** [comment]
Actually if you watch the video you can see it all.

The service I am using is Yahoo.

The log that I got is just like this:

Uncaught ReferenceError: super_res is not defined

---

http://192.168.100.5:8079/web/js/web.assets_backend/0ee08b8:3937

It happen when I want to choose the currencies in many2many field.

Thank You.

Best Regards,

Hans Yonathan

Odoo Support

FALINWA Limited

Expert in Finance, Information System & Business Intelligence

Odoo Silver Partner

Website:  http://www.falinwa.com/ www.falinwa.com

Tel. 13670137019 (China - Shenzhen)

**Comment by feketemihai** [comment]
I cannot reproduce your bug...and strange is that in the code there isn't any super method...so this has to deal with something else...the best way is to put here the errors from the log...
