### ISSUE TITLE
bug account_check_deposit doesn't work in multi compagny setup

### ISSUE THREAD

**Issue by babatoko** [OCA/account-financial-tools#1059]
I use check deposit module for a while and after upgrading from odoo10 to odoo12 I'm not able to create a new check deposit.

The field journal doesn't show up.

I'm not able to reproduce on run it as my multi-company setup.

Cheers for your help

**Comment by babatoko** [comment]
Hi

Did someone have seen this issue?

Any clue to go forward

Cheers

**Comment by babatoko** [comment]
Right, @alexis-via

odoo version: 12.0 community

module in use into scope context of the issue:
base_multi_company
account_check_deposit

maybe others

![Screenshot_20210509_115358-1](https://user-images.githubusercontent.com/14819240/117568134-2f13c900-b0bf-11eb-81c0-bd68371c0509.png)

When i'm in a multi-compagny contexte account_check_deposit should use different journal one for each company. In that case it doesn't show any.

**Comment by pedrobaeza** [comment]
`base_multi_company` by itself is not doing anything, so you can remove it.

**Comment by babatoko** [comment]
I have some compagnies into the same database and I thought that this module is the main one. As it's difficult to enum all module dependency.

Is there a way to get more information?

**Comment by farazbdm** [comment]
@babatoko check that the journal you are looking for has in it the related Bank Account Configured
as for this field (journal) there is a domain to show only journals with bank account details set on them

**Comment by alexis-via** [comment]
@farazc2h It is the opposite: the field "Journal" highlighted on the screenshot should NOT be linked to a bank account.
Anyway, there is no bug here, this is just a configuration issue.
I use this module in many multi-company deployments and there is no such pb.
