### ISSUE TITLE
Function email send

### ISSUE THREAD

**Issue by malogo** [OCA/account-financial-tools#1067]
I have a boolean variable to control the sending of delinquent payment notices. But I don't know where in the code this function is.

**Comment by pedrobaeza** [comment]
Which module in this repository?

**Comment by malogo** [comment]
Acount credit control

**Comment by pedrobaeza** [comment]
But which is the bug? Which Odoo version?

**Comment by malogo** [comment]
No es un bug como tal, tenemos clientes que no pueden ser tratados como morosos, como la Xunta de Galicia y generé una variable para que cuando se vaya a lanzar los emails a los "morosos" se controle que a esos clientes, con la variable a TRUE, no se les envíe. Pero no encuentro el punto en el código donde se gestiona dicho envío

**Comment by malogo** [comment]
version Odoo 10.0

**Comment by pedrobaeza** [comment]
Only in English. Sorry, but this is an issue tracker, only for commenting bugs, so closing this. Please do your question in forums or mailing lists.
