### ISSUE TITLE
[13.0] account_asset_management - Created Moves are initially as posted

### ISSUE THREAD

**Issue by FedericoGregori** [OCA/account-financial-tools#1075]
Hi guys. First time reporting an issue, if the format or something is wrong please sorry. Still learning.

I don't fully understand why the Create Move button on Account Asset Lines automatically post the Account Move. I mean, after we created one, is impossible to cancel/delete it and you enter in some kind of "deletion" bucle where you need to change the state of the Asset to draft but still not available to delete the Account Move.

Removing the move.post() line in create_move method fixes the bucle.

![image](https://user-images.githubusercontent.com/22988134/97335912-28c5aa00-185d-11eb-90ba-f849704a7d4a.png)

Is this intentionally?

**Comment by pedrobaeza** [comment]
I don't get why you aren't able to cancel it after the creation...

**Comment by FedericoGregori** [comment]
If you try to delete an Account Move from the Asset Line you get:
![image](https://user-images.githubusercontent.com/22988134/97337556-34b26b80-185f-11eb-898b-0d801221b0b6.png)

Then you go to the Account Move Form and it requests to change the Asset to draft
![image](https://user-images.githubusercontent.com/22988134/97337665-54e22a80-185f-11eb-8155-c299cfa80a0d.png)

After that the next error is saying this:
![image](https://user-images.githubusercontent.com/22988134/97337783-78a57080-185f-11eb-9da4-c21d6968792a.png)

But the Asset only have this related Account Move created.

**Comment by pedrobaeza** [comment]
But if you delete the move from the button in the depreciation board, is it not working?

**Comment by FedericoGregori** [comment]
No, I get the next two alerts:
![image](https://user-images.githubusercontent.com/22988134/97345388-c1adf280-1868-11eb-926e-34a517124feb.png)

![image](https://user-images.githubusercontent.com/22988134/97345408-c8d50080-1868-11eb-8ace-b0da8566cade.png)

- Atm the delete move button works only if the account move is in draft. But this behavior is achieved only if the move.post() is removed/commented.

**Comment by pedrobaeza** [comment]
One last question: are you able to set to draft the depreciation move and then delete it?

**Comment by FedericoGregori** [comment]
No, Im not. I get this:

![image](https://user-images.githubusercontent.com/22988134/97346065-b60efb80-1869-11eb-82fa-8aa7f8ff2c2c.png)

**Comment by pedrobaeza** [comment]
OK, thanks for the extensive tests and information.

@luc-demeyer what do you think it should be the flow?

A. Allow to delete posted/draft depreciation moves from asset depreciation board?
B. Allow to delete draft depreciation moves from asset depreciation board and allow to set to draft from move view?
C. Allow to delete draft depreciation moves no matter from which view and allow to set to draft from move view?
