### ISSUE TITLE
[12.0] account-asset-management: Calculation of fiscal year duration makes no sense in non-trivial cases 

### ISSUE THREAD

**Issue by svalaeys** [OCA/account-financial-tools#1076]
Hello,

Some customers of mine reported that the value of depreciations in the depreciation board were not constant as expected over each month. It didn't fit the "urgent to figure out" until this happened:
![image](https://user-images.githubusercontent.com/8061624/97539278-fd100480-19c1-11eb-889c-4774253f5085.png)

There is actually a negative depreciation for a month.

To reproduce this, which I've done on the odoobot visible in the picture, you must:

Create the following three fiscal years:
- July 1st 2018 to June 30th 2019
- July 1st 2019 to June 30th 2020
- July 1st 2020 to June 30th 2021 (although I don't think this one is necessary, but anyway)

Create an asset category with linear depreciation per month for, in my case, 10 years, and prorata temporis.

Create a new asset  with a start date of January 31st, 2019. and a value of 7237.80.

Just for good measure, we can all agree that any regular month should be 7237.80 / 120 = 60.31, which the depreciation board gets right on most entries. So let's focus on the two I highlight.

Let's start with the bottom number I highlighted.

This higher amount than it should be is because the factor for the year is computed to 1.0013773486039375. So while the method _compute_year_amount correctly returns 723.78 as a yearly amount, with the factor that amount becomes 724.78. When the system computes the final period, it therefore errs. So why is the factor greater then one? Because the system adds two ratios: the number of included days / the number of days total in 2018 + the number of included days / the number of days total in 2019 in the _get_fy_duration method. In this particular use case this makes no sense. The fiscal year ratio is 1, not anything else.

It turns out it is a similar problem for the negative amount. The method _get_fy_duration_factor finds that there are 151 days from Jan 31st to Jun 30th, and therefore, because the entire year has 365 days, the ratio is 0.4136986301369863. So for the first year, the amount is computed by the system to be 299.42679452054796. Then later in _get_first_period_amount the system rightly detects 5 periods. So when it attempts to fin the value of the first period (the one day in Jan), it goes 299.42679 - 5 * 60.315, which is negative

I am not sure that the solution is trivial, so before I rack my brain, I would really appreciate if I am doing something wrong or if you can confirm this.

Thanks a bunch.

**Comment by pedrobaeza** [comment]
Without investigating too much, have you tried with the check "Calculate by days"?

**Comment by luc-demeyer** [comment]
This could be a duplicate of the issue tackled in https://github.com/OCA/account-financial-tools/pull/925

**Comment by svalaeys** [comment]
@pedrobaeza If I try with Calculate by days, for the first period I get a positive 1.98, which sounds about right.

@luc-demeyer Insofar as I can undesrtand #925  seems to be related to leap years. In my case that's not (entirely) the problem. The first fiscal year involves no leap years (2018 and 2019). However, the problem is that the ratio is computed based on days, and that seems to me to just not a suitable approach if you don't select the calculation by days. As described in the previous post, the system computes that the period between Jan 31st and June 30th is 0.4136986 of the year, where as in terms of periods is five periods + 1 day. So 1 / 12 * 5 + 1/ 360 (12 months of thrity days) = 0.4194444444. If I use this ratio, I get an amount for the first year of 723.78 * 0.419444444 = 303.5833. Then if I substract 5 periods, I get 2.015.  Which is exactly 723.78 / 360. 

Is it controversial to assume that a computation that does not depend on days can be computed based on a 360-day year like I often do? If not, we could simply amend the duration calculation to compute the number of full periods plus the number a number of days.
