### ISSUE TITLE
account_asset_management catalan i18n

### ISSUE THREAD

**Issue by enricostano** [OCA/account-financial-tools#1114]
Hi,
in Weblate I see that catalan language is present in 2 files `ca.po` and `ca_ES.po`:
![image](https://user-images.githubusercontent.com/748971/105733377-c9496a00-5f31-11eb-8a30-db1f8593fcc0.png)
Which one should we use?
Should we merge them? Which one should be present? I guess `ca.po`.

Thanks!

**Comment by pedrobaeza** [comment]
Yes, you can do a PR removing `ca_ES.po`.
