### ISSUE TITLE
[account_asset_management] Deferred revenues and expenses

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-tools#1128]
The account asset management module can be used to compute deferred revenues and expenses as well.

So, you enter a vendor bill, and indicate a deferred expense account. This creates an asset. The asset profile in this case involves the following accounts:

- **Asset account:** Deferred expense account
- **Accumulated Depreciation account:**  Deferred expense account
- **Depreciation expense account:** Expense account

The journal entries would be:

1) At the time of vendor bill posting
Dr. Deferred Expense (was asset account)
Cr. Accounts payable 

2) Depreciations from the depreciation board
Dr. Expense (was depreciation expense account)
Cr. Deferred Expense (was accumulated depreciation account)

In this case parameters such as salvage value, or the option to remove the asset do not make any sense.

In my opinion we could define a field 'asset_type' with values ('Asset', 'Deferred Expense', 'Deferred Revenue') and have separate menus to handle each type.

cc @pedrobaeza @luc-demeyer @etobella

**Comment by etobella** [comment]
LGTM, maybe we need to use `asset` as default.

**Comment by pedrobaeza** [comment]
AFAIK, this case is covered with account-closing modules (cutoff ones). I don't know if mixing them with assets is a good option.

**Comment by JordiBForgeFlow** [comment]
@alexis-via Could you comment on this? Do you agree with Pedro? I agree that the cutoff modules seem to do the job.

**Comment by luc-demeyer** [comment]
Several of my customers use the account_asset_management module for this purpose since OpenERP v6.
Technically it works ok, but from a User Interface standpoint it's not intuitive.
An alternative is https://github.com/OCA/account-financial-tools/tree/12.0/account_spread_cost_revenue.

**Comment by JordiBForgeFlow** [comment]
@luc-demeyer looks like account_spread_cost_revenue is what I was looking for! And almost migrated to v13! https://github.com/OCA/account-financial-tools/pull/984

The benefit of this module is that is so much more intuitive than the cut-off ones, because the prepaid expense is recognized at the beginning as an asset, to be expensed out of a predefined board. This means that at any point of time when you run your balance sheet, it truly reflects the right status of your company. It makes a difference between different types of prepaid expenses, whereas the cut-off modules use a single account for pre-paid expenses that can be very confusing.

cc @AdriaGForgeFlow @alexis-via

**Comment by astirpe** [comment]
@JordiBForgeFlow you may find interesting the discussion about the difference between the spread-cost-revenue module and the cut-off modules here: https://github.com/OCA/account-financial-tools/pull/715

**Comment by JordiBForgeFlow** [comment]
@astirpe thanks!! Closing the issue
