### ISSUE TITLE
account_auto_fy_sequence: access rights issue

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-financial-tools#113]
For example, I use accout_auto_fy_sequence with the module donation_tax_receipt ; the tax receipts use a sequence with "%(fy)s". When a regular user creates a tax receipt, if he is the first to do it for a fiscal year, he will get an access rights error pop-up that says that he doesn't have "create" access on ir.sequence:

Sorry, you are not allowed to create this kind of document. Only users with the following access level are currently allowed to do that:
- Point of Sale/Manager
- Administration/Settings
  (Document model: ir.sequence) 

The reason is obvious: In account_auto_fy_sequence/ir_sequence.py, a call to _next() may lead to the automatic creation of a new ir.sequence, and this creating is made with the uid of the current user... and only members of Administration/Settings have "create" rights on ir.sequence.

So I think that the creation should be made with SUPERUSER_ID

**Comment by pedrobaeza** [comment]
You're totally right. Are you going to do the corresponding PRs (7.0 and 8.0)?
