### ISSUE TITLE
error installing odoo 12 missing python-dateutil

### ISSUE THREAD

**Issue by jotate70** [OCA/account-financial-tools#1132]
Hello when installing in odoo 12 it throws me the following error, Impossible to install the module "account_asset management" because there is an unresolved external dependency: No module named python-dateutil

**Comment by sergiocorato** [comment]
This is a required library, to solve the issue install it.

**Comment by jotate70** [comment]
hello, python-dateutil 2.8.1 is installed but the error message still appears

**Comment by pedrobaeza** [comment]
Not in the Python environment where you are running Odoo. If installed, it won't show that error.
