### ISSUE TITLE
[14] account_auto_fy_sequence : Migration to Odoo14 CE

### ISSUE THREAD

**Issue by yboujraf** [OCA/account-financial-tools#1155]
module: account_auto_fy_sequence
version: 8.0

I am using this module in my OdOO V8 CE.

Now I am migrating in Odoo 14 CE but I can't find the module or equivalent.

Any idea will be nice.

Best Regards

**Comment by kittiu** [comment]
I think this module is not needed, as Odoo CE already sequense reset already works.
