### ISSUE TITLE
[12] account_asset_management - the number of the entry number is the name of the asset

### ISSUE THREAD

**Issue by ghost** [OCA/account-financial-tools#1164]
Hello,
I have detected the following behavior in runbot. When posting the entries, Odoo assigns them the name of the asset instead of the corresponding entry number. I think it is not correct.
The steps I have followed are:

I have created an Asset Categories
![2021-04-22 13_03_20-Elementos de transporte - Odoo](https://user-images.githubusercontent.com/25029267/115707441-155c4d00-a36f-11eb-812c-96439a447dcd.png)

The entries are posted to the following journal in the following sequence:
![2021-04-22 13_05_11-Journal Entries Sequence - Odoo](https://user-images.githubusercontent.com/25029267/115707473-2016e200-a36f-11eb-8be1-b631f9e1aeda.png)

I have created the asset and called it test
![2021-04-22 13_00_05-test - Odoo](https://user-images.githubusercontent.com/25029267/115707499-27d68680-a36f-11eb-8a86-25b7894b76cd.png)

When accounting for the amortization entries, it has given them the number "test"
![2021-04-22 13_00_22-Window](https://user-images.githubusercontent.com/25029267/115707519-2f962b00-a36f-11eb-8ca8-4e5d7a82c330.png)
![2021-04-22 12_59_52-test - Odoo](https://user-images.githubusercontent.com/25029267/115707543-3886fc80-a36f-11eb-8aba-e23251c34c83.png)

**Comment by pedrobaeza** [comment]
Duplicated of #1008
