### ISSUE TITLE
[14] Edit journals and sequences like version 13 - ENHANCEMENT

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/account-financial-tools#1171]
In odoo 14 CE is not possible to edit journals and sequences as in older versions.  In odoo apps we can find three or more paid modules that solve this problem. As an example
https://apps.odoo.com/apps/modules/14.0/cf_journal_sequence/

**Comment by kittiu** [comment]
We are developing this module (actually it is done), you can help review? It is does not work the same way, but with intention to be more flexible (and not just for accounting).
https://github.com/OCA/account-invoicing/pull/932
