### ISSUE TITLE
bug account_check_deposit doesn't work in multi compagny setup

### ISSUE THREAD

**Issue by babatoko** [OCA/account-financial-tools#1179]
account_check_deposit seems not to be working in multi company environnement.

Not able to test onto runbot.

I'm fully available to help

**Comment by babatoko** [comment]
ping @pedrobaeza @sbidoul

**Comment by pedrobaeza** [comment]
Please don't ping randomly. We are not involved in such module. Check contributors of it.

**Comment by babatoko** [comment]
I don't ping randomly and use what is available on github. 

Is the contributor list is in __manifest__.py of account_check_deposit. Is that correct

**Comment by pedrobaeza** [comment]
Stéphane has nothing to do with this module. We contributed a lot of time ago (11.0). I think you want to ping @alexis-via. Anyway, you are not even saying which Odoo version and why is not compatible.

**Comment by babatoko** [comment]
Right,  @alexis-via

Odoo 12.0 and the problem is partialy discribe in #1059.

![Screenshot_20210509_115358-1](https://user-images.githubusercontent.com/14819240/117567751-d2fc7500-b0bd-11eb-8fe8-769436577abc.png)

It's not possible to select the journal, it doesn't show up.

I have multi-compagny module install.

**Comment by pedrobaeza** [comment]
Then why duplicating the issue? Please complete the other one with more data to reproduce the problem. Which multi-company module? Anyways, closing this one, and please write on the other.
