### ISSUE TITLE
New module for setting accounts balances to 0

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/account-financial-tools#1210]
We're planning to add a new module for setting account balances to 0.

Imagine this use case:

- One of our clients has only been using invoicing (but not accounting) for several years. An external company was carrying out this duties instead of them.
- They'll start using accounting features (let's say) in 01/01/2022.
- For starting as clean as possible, we would do a manual account move to set the accounts balances to 0.

We realised that doing it manually might be a headache. Importing is not the best way, as well.

Our idea is to create a module like "account_set_balance_to_zero" that would be structured (in broad terms) like:

- A wizard where user could set a limit date (let's say before 01/01/2022) and calculate the account move lines.
- User would be able to filter by accounts, partner... (similar to account_financial_report module, you know)
- This calculation would show the account balance for each account move line and considering partners, analytic accounts, taxes... as well.
- Another button would create an "inverse" account move.
- After validating this new inverse account move, this would set the balance to 0 when starting on 01/01/2022.

The idea is to "clean" the accounting balance as much as possible by the easiest way.

Do you consider that this would be useful for OCA?

@pedrobaeza @JordiBForgeFlow @sbidoul 

THX

**Comment by pedrobaeza** [comment]
I don't think such module must be an "official" one, as that's a dirty patch for something done incorrect.

**Comment by HaraldPanten** [comment]
> I don't think such module must be an "official" one, as that's a dirty patch for something done incorrect.

Yep, I know... But sometimes some of these projects come from other Odoo partners or the client started using Odoo on his own.

You know that sometimes you can not start with "clean" projects starting from 0.

OK, we'll do that in our public repo. I'll publish the link here once we've finished. THX Pedro.
