### ISSUE TITLE
[14.0] account_loan: needed explicit acl for transient model account.loan.post

### ISSUE THREAD

**Issue by cubells** [OCA/account-financial-tools#1327]
As stated in migration notes: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

in version 14.0 when we define a transient model , an acl line is needed.

If not an error is raised 

![2022-02-03_07-53](https://user-images.githubusercontent.com/4386443/152295186-98f208eb-f608-4101-92dd-49203ac93824.png)

cc @AntoniRomera

**Comment by AaronHForgeFlow** [comment]
FIX merged. Thanks!

**Comment by pleirb** [comment]
How's everybody? The same thing happens to me after migrating from 13 to 14. Is it related to account-financial-tools or could the problem be other modules? What do you suggest me to do? In principle it does not give me a problem but this error is passed to the following versions that I want to migrate. Attached image:
![image](https://github.com/OCA/account-financial-tools/assets/2092475/7c4a678c-8a5b-4b74-b2b0-55707338e915)

**Comment by etobella** [comment]
Upgrade to last version of the module

**Comment by pleirb** [comment]
@etobella  I'm using doodba for oca repositories and I'm supposed to be using the updated modules. I don't know what it could be. Thanks for the reply

**Comment by pleirb** [comment]
I have solved it by granting the access rights from the user interface, in configuration -> Technical -> Security -> Access Control List and leaving the ir.property objects like this:
![image](https://github.com/OCA/account-financial-tools/assets/2092475/6c29b935-96bd-473d-8905-db44d84ffb5e)
