### ISSUE TITLE
account_asset_management showing twice the menu: "Invoicing->Configuration->Asset-> Asset Categories"

### ISSUE THREAD

**Issue by AnouarMarrakchi** [OCA/account-financial-tools#1383]
Hi Team

## Module
"**account_asset_management**"

## Describe the bug
We have installed Odoo 14 community version including "**account_asset_management**" module as shown on the screenshot below:
 
![image](https://user-images.githubusercontent.com/81482928/165072967-2c452cd1-55da-4dec-ba96-22d7277cff62.png)

I would like to report that I have noticed that the menu: "**Invoicing->Configuration->Asset-> Asset Categories**" appears twice with the same name as shown on the screenshot below:
![image](https://user-images.githubusercontent.com/81482928/165073596-55793dc3-43c7-4692-b466-d345da3e9adc.png)

When accessing the first Asset categories menu from the top the displayed view is:
![image](https://user-images.githubusercontent.com/81482928/165074450-354b903f-9968-4ed1-9530-d68387436181.png)

When accessing the second Asset categories menu from the top the displayed view is:
![image](https://user-images.githubusercontent.com/81482928/165074762-c1bda3eb-11ac-4e0a-9a7a-5b4bd264cac8.png)

## To Reproduce

1. Install Odoo v14
2. Install "**account_asset_management**" module 
3. Access the "**Invoicing->Configuration->Asset-> Asset Categories**" menus

**Expected behavior**
According to the module installed features of "**account_asset_management**" module there should be the following created menus .
Among which the menus **Asset Groups** and **Asset profiles** are missing, it may be a error regarding the naming of those two menus 

> Invoicing/Assets
> Invoicing/Assets/Assets
> Invoicing/Assets/Compute Assets
> Invoicing/Configuration/Assets
> **Invoicing/Configuration/Assets/Asset Groups**
> **Invoicing/Configuration/Assets/Asset Profiles**
> Invoicing/Reporting/Financial Assets
> Invoicing/Reporting/Financial Assets/Financial Assets report

**Additional context**
Created views after the installation:
*** INHERIT Journal Items (Search) (search)
* INHERIT Journal Items (form) (form)
* INHERIT account.account.form (form)
* INHERIT account.move.form.account.asset.management (form)
Financial Assets report (form)
account.asset.compute (form)
account.asset.compute.result (form)
account.asset.form (form)
account.asset.group.form (form)
account.asset.group.search (search)
account.asset.group.tree (tree)
account.asset.profile.form (form)
account.asset.profile.search (search)
account.asset.profile.tree (tree)
account.asset.remove.form (form)
account.asset.search (search)
account.asset.tree (tree)
wiz.asset.move.reverse.form (form)**

Thank you in advance for the feedback and regards

**Comment by AnouarMarrakchi** [comment]
Any replies?

**Comment by luc-demeyer** [comment]
technically there are only asset profiles and asset groups.
But several translation groups translate both of these complete different terms to categories.
Issue to be fixed by the translation groups.
