### ISSUE TITLE
account_chart_update

### ISSUE THREAD

**Issue by kristoft** [OCA/account-financial-tools#1430]
When updating towards version 14.0.2.3 i get this error : 

Veld "update_tax_repartition_line_account" bestaat niet in model "wizard.update.charts.accounts"

View name: Update Chart of Accounts from a Chart Template
Error context:
 view: ir.ui.view(1202,)
 xmlid: view_update_multi_chart
 view.model: wizard.update.charts.accounts
 file: /bitnami/odoo/addons/account_chart_update/wizard/wizard_chart_update_view.xml

When i check the .XML file the field does exist, is there any way to solve this ?

Full error :

The above exception was the direct cause of the following exception:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/models.py", line 4201, in _load_records
    data['record']._load_records_write(data['values'])
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 1842, in _load_records_write
    super(View, self)._load_records_write(values)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/models.py", line 4138, in _load_records_write
    self.write(values)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/models.py", line 3696, in write
    fields[0].determine_inverse(real_recs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/fields.py", line 1187, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/models.py", line 3686, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/models.py", line 1266, in _validate_fields
    check(self)
  File "/bitnami/odoo/addons/web_tree_decoration_underline/models/ir_ui_view.py", line 19, in _check_xml
    return super()._check_xml()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 3 more times]
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 954, in postprocess
    validator(node, name_manager, node_info)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 1090, in _validate_tag_field
    self.handle_view_error(msg)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Fout bij het valideren van weergave:

Veld "update_tax_repartition_line_account" bestaat niet in model "wizard.update.charts.accounts"

View name: Update Chart of Accounts from a Chart Template
Error context:
 view: ir.ui.view(1202,)
 xmlid: view_update_multi_chart
 view.model: wizard.update.charts.accounts
 file: /bitnami/odoo/addons/account_chart_update/wizard/wizard_chart_update_view.xml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_upgrade
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_module.py", line 654, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/odoo/lib/odoo-14.0.post20211110-py3.8.egg/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /bitnami/odoo/addons/account_chart_update/wizard/wizard_chart_update_view.xml:5, near
<record id="view_update_multi_chart" model="ir.ui.view">
        <field name="name">Update Chart of Accounts from a Chart Template</field>
        <field name="model">wizard.update.charts.accounts</field>
        <field name="arch" type="xml">
            <form>
                <header>
                    <field name="state" select="2" widget="statusbar" statusbar_visible="init,ready,done" statusbar_colors="{&quot;ready&quot;:&quot;blue&quot;,&quot;done&quot;:&quot;blue&quot;}"/>
                </header>
                <group attrs="{'invisible':[('state','!=','init')]}">
                    <h3>
                        <p>
                            <center>
                            This wizard will update your accounts, taxes and
                            fiscal positions according to the selected chart
                            template
                        </center>
                        </p>
                    </h3>
                </group>
                <group string="Chart of Accounts" attrs="{'invisible':[('state','!=','init')]}">
                    <field name="company_id" attrs="{'invisible':[('state','!=','init')]}"/>
                    <field name="code_digits" invisible="1"/>
                    <field name="chart_template_id" domain="[('visible', '=', True)]" attrs="{'invisible': [('state','!=','init')], 'required': True}"/>
                    <field name="lang" attrs="{'invisible':[('state','!=','init')]}"/>
                </group>
                <notebook attrs="{'invisible':[('state','!=','init')]}">
                    <page string="General options" name="page_general_options">
                        <group>
                            <group string="Update records?">
                                <field name="update_tax"/>
                                <field name="update_account"/>
                                <field name="update_fiscal_position"/>
                            </group>
                            <group string="Other options" attrs="{'invisible':[('state','!=','init')]}">
                                <field name="continue_on_errors"/>
                                <field name="recreate_xml_ids"/>
                            </group>
                        </group>
                        <group>
                            <h5>
                                <p>
                                If you leave these options set, the wizard will
                                not just create new records, but also update
                                records with changes (i.e. different tax amount)
                            </p>
                                <p>
                                Note: Only the changed fields are updated.
                            </p>
                            </h5>
                        </group>
                    </page>
                    <page string="Field options" attrs="{'invisible': [                           ('update_tax', '=', False),                           ('update_account', '=', False),                           ('update_fiscal_position', '=', False),                       ]}">
                        <h3>
                            <p>
                            Here you can select the fields you want to check if
                            they have been updated in the templates.
                        </p>
                        </h3>
                        <notebook>
                            <page string="Taxes" name="page_fields_taxes" attrs="{'invisible': [('update_tax', '=', False)]}">
                                <group>
                                    <field name="update_tax_repartition_line_account" attrs="{'invisible':[('update_tax', '=', False)]}"/>
                                    <field name="update_tax_repartition_line_tags" attrs="{'invisible':[('update_tax', '=', False)]}"/>
                                </group>
                                <field name="tax_field_ids" widget="many2many_checkboxes" context="{'account_chart_update': True}"/>
                            </page>
                            <page string="Accounts" name="page_fields_accounts" attrs="{'invisible': [('update_account', '=', False)]}">
                                <field name="account_field_ids" widget="many2many_checkboxes" context="{'account_chart_update': True}"/>
                            </page>
                            <page string="Fiscal positions" name="page_fields_fps" attrs="{'invisible': [('update_fiscal_position', '=', False)]}">
                                <field name="fp_field_ids" widget="many2many_checkboxes" context="{'account_chart_update': True}"/>
                            </page>
                        </notebook>
                    </page>
                    <page string="Matching" attrs="{'invisible': [                           ('update_tax', '=', False),                           ('update_account', '=', False),                           ('update_fiscal_position', '=', False),                       ]}">
                        <h3>
                            <p>Here you can set the matching order.</p>
                        </h3>
                        <notebook>
                            <page string="Taxes" name="page_matching_taxes" attrs="{'invisible': [('update_tax', '=', False)]}">
                                <field name="tax_matching_ids">
                                    <tree create="false" edit="false" default_order="sequence">
                                        <field name="sequence" widget="handle"/>
                                        <field name="matching_value"/>
                                    </tree>
                                    <form>
                                        <field name="matching_value" readonly="1"/>
                                    </form>
                                </field>
                            </page>
                            <page string="Accounts" name="page_matching_accounts" attrs="{'invisible': [('update_account', '=', False)]}">
                                <field name="account_matching_ids">
                                    <tree create="false" edit="false" default_order="sequence">
                                        <field name="sequence" widget="handle"/>
                                        <field name="matching_value"/>
                                    </tree>
                                    <form>
                                        <field name="matching_value" readonly="1"/>
                                    </form>
                                </field>
                            </page>
                            <page string="Fiscal positions" name="page_matching_fps" attrs="{'invisible': [('update_fiscal_position', '=', False)]}">
                                <field name="fp_matching_ids">
                                    <tree create="false" edit="false" default_order="sequence">
                                        <field name="sequence" widget="handle"/>
                                        <field name="matching_value"/>
                                    </tree>
                                    <form>
                                        <field name="matching_value" readonly="1"/>
                                    </form>
                                </field>
                            </page>
                        </notebook>
                    </page>
                </notebook>
                <group attrs="{'invisible':[('state','!=','ready'),]}" string="Records to create/update">
                    <notebook colspan="4">
                        <page string="Taxes" attrs="{'invisible': [('update_tax', '=', False)]}">
                            <field name="tax_ids" nolabel="1">
                                <tree string="Taxes" colors="red:type=='updated'">
                                    <field name="tax_id"/>
                                    <field name="update_tax_id"/>
                                    <field name="type_tax_use"/>
                                    <field name="notes"/>
                                    <field name="type"/>
                                </tree>
                                <form>
                                    <group col="2">
                                        <group>
                                            <field name="recreate_xml_ids" invisible="1"/>
                                            <field name="tax_id"/>
                                            <field name="type" attrs="{'readonly': [('recreate_xml_ids','=', False)]}"/>
                                            <field name="notes"/>
                                        </group>
                                        <group>
                                            <field name="update_chart_wizard_id"/>
                                            <field name="type_tax_use"/>
                                            <field name="update_tax_id"/>
                                        </group>
                                    </group>
                                </form>
                            </field>
                        </page>
                        <page string="Accounts" attrs="{'invisible': [('update_account', '=', False)]}">
                            <field name="account_ids" nolabel="1">
                                <tree string="Accounts" colors="red:type=='updated'">
                                    <field name="account_id"/>
                                    <field name="update_account_id"/>
                                    <field name="notes"/>
                                    <field name="type"/>
                                </tree>
                                <form>
                                    <group col="2">
                                        <group>
                                            <field name="recreate_xml_ids" invisible="1"/>
                                            <field name="account_id"/>
                                            <field name="type" attrs="{'readonly': [('recreate_xml_ids','=', False)]}"/>
                                            <field name="notes"/>
                                        </group>
                                        <group>
                                            <field name="update_chart_wizard_id"/>
                                            <field name="update_account_id"/>
                                        </group>
                                    </group>
                                </form>
                            </field>
                        </page>
                        <page string="Fiscal positions" attrs="{'invisible': [('update_fiscal_position', '=', False)]}">
                            <field name="fiscal_position_ids" nolabel="1">
                                <tree string="Fiscal positions" colors="red:type=='updated'">
                                    <field name="fiscal_position_id"/>
                                    <field name="update_fiscal_position_id"/>
                                    <field name="notes"/>
                                    <field name="type"/>
                                </tree>
                                <form>
                                    <group col="2">
                                        <group>
                                            <field name="recreate_xml_ids" invisible="1"/>
                                            <field name="fiscal_position_id"/>
                                            <field name="type" attrs="{'readonly': [('recreate_xml_ids','=', False)]}"/>
                                            <field name="notes"/>
                                        </group>
                                        <group>
                                            <field name="update_chart_wizard_id"/>
                                            <field name="update_fiscal_position_id"/>
                                        </group>
                                    </group>
                                </form>
                            </field>
                        </page>
                    </notebook>
                </group>
                <group col="4" colspan="4" attrs="{'invisible':[('state','!=','done'),]}">
                    <separator colspan="4" string="Log"/>
                    <field name="log" colspan="4" nolabel="1"/>
                    <group colspan="4">
                        <separator colspan="4" string="Summary of created objects"/>
                        <field name="new_taxes"/>
                        <field name="new_accounts"/>
                        <field name="new_fps"/>
                    </group>
                    <group colspan="4">
                        <separator colspan="4" string="Summary of updated objects"/>
                        <field name="updated_taxes"/>
                        <field name="deleted_taxes"/>
                        <field name="updated_accounts"/>
                        <field name="updated_fps"/>
                    </group>
                </group>
                <footer>
                    <span states="init">
                        <button name="action_find_records" string="Next" class="oe_highlight" type="object"/>
                    </span>
                    <span states="ready">
                        <button name="action_init" string="Previous" type="object"/>
                        <button name="action_update_records" string="Create/Update" type="object" class="oe_highlight"/>
                    </span>
                    <span states="init,ready"> or </span>
                    <button special="cancel" string="Close" class="oe_link"/>
                </footer>
            </form>
        </field>
    </record>

**Comment by pedrobaeza** [comment]
You haven't do the module upgrade inside Odoo DB, but nothing to do with the module itself.

**Comment by kristoft** [comment]
I did start the update from inside Odoo , what do you mean inside Odoo ??

**Comment by pedrobaeza** [comment]
Restart the Odoo service then.

**Comment by kristoft** [comment]
This does the trick , thanks !
