### ISSUE TITLE
Account_Move_Print: Print old "Account Display Name"

### ISSUE THREAD

**Issue by EngNassar** [OCA/account-financial-tools#1447]
When printing any Journal, it print the account name in old names which already changed....

## Module
Accounting: Journal Entries Print

## Describe the bug
When changing name of any account, and create a new journal including the updated account, it appears in the print out in old name.

## To Reproduce
**Affected versions**: 15.0+e (Enterprise Edition)

1. Change Account name in "Chart of Accounts" page
2. Create a new Journal Entry
3. Use same account which was updated by changing the name
4. Save and print through "Journal Entries" print

**Expected behavior**
Account name in the printout should be in new name.

**Additional context**
N/A

**Comment by EngNassar** [comment]
Hello...any reply on above issue?

Your quick response is highly required and appreciated.

Thank you.

**Comment by EngNassar** [comment]
Hello,

Any updates or reply on above issue?

**Comment by EngNassar** [comment]
Hellooooooooooo,,,,

It is 11 days since I created this issue!!!!!

**Comment by rafaelbn** [comment]
Hello @EngNassar , thank you for the issue.

OCA is a non-profit organization , we appreciate you feedback but nobody works fixing issues or answering. All are contributions, so you have to wait o fix it directly with a developer making a Pull request. There is not responsibility in this modules from OCA o original authors.

Also I see you have never done a review of a Pull Request, meaning that you have never contributed. Don 't worry, some time it difficult, you can check this video from Daniel Reis explaining how you could contribute https://youtu.be/mMTc2_Qn8Mw

Thank you very much again.
Regards

Maybe @emadshaaban92 you could check it.
