### ISSUE TITLE
[14.0, 15.0] account_move_name_sequence: default of account.journal field 'refund_sequence' not respected in method 'create'

### ISSUE THREAD

**Issue by azoellner** [OCA/account-financial-tools#1465]
In module "account_move_name_sequence" (of branches "14.0" and "15.0"), the default of `account.journal` field `refund_sequence` is changed to `True`. (Compare e.g. the [original in module "account" of branch "14.0"](https://github.com/odoo/odoo/blob/3d2a1ab1adb797ab45d29ff1016e1fc3f4d88b13/addons/account/models/account_journal.py#L123)). But this changed default value then is not taken into account in the overwritten method `create()`.

### Expected behavior
There should actually be a `refund_sequence_id` whenever the `refund_sequence` is `True`.

### Current behavior
If not explicitly providing the `refund_sequence` (and also no explicit `refund_sequence_id`) when creating an `account.journal` record of type "sale" or "purchase", no `refund_sequence_id` will get created, but `refund_sequence` will be `True`.

### Causes
In module "account", the value of field `refund_sequence` [is explicitly added](https://github.com/odoo/odoo/blob/3d2a1ab1adb797ab45d29ff1016e1fc3f4d88b13/addons/account/models/account_journal.py#L559-L561) to the argument `vals` during `create()`, by calling `_fill_missing_values()`: For "sale" and "purchase" journals, it will be `True`, and `False` for all other journal types.
But here in module "account_move_name_sequence", this super method `create()` is called (and correctly so) only _after_ the creation of the sequences.
As a consequence, if not explicitly providing `refund_sequence` (and also no `refund_sequence_id`) when creating an `account.journal` record of type "sale" or "purchase", [no `refund_sequence_id` will get created](https://github.com/OCA/account-financial-tools/blob/4b3bb15b213d4faacab454aa7891ca46d76e4c2d/account_move_name_sequence/models/account_journal.py#L73-L78) (because `vals.get("refund_sequence")` will be `False`). But then during the super call, field `refund_sequence` will be set to `True`.

### Proposed fix
As a fix, do add `True` as the explicit default when [getting `refund_sequence` from the `vals`](https://github.com/OCA/account-financial-tools/blob/4b3bb15b213d4faacab454aa7891ca46d76e4c2d/account_move_name_sequence/models/account_journal.py#L75):
```diff
             vals["sequence_id"] = self._create_sequence(vals).id
         if (
             vals.get("type") in ("sale", "purchase")
-            and vals.get("refund_sequence")
+            and vals.get("refund_sequence", True)
             and not vals.get("refund_sequence_id")
         ):
             vals["refund_sequence_id"] = self._create_sequence(vals, refund=True).id
```

In general, getting a value from the `vals` should always be done with the same default as the field's definition.

**Comment by RodrigoBM** [comment]
Same bug in V16.0 i am resolve it in PR https://github.com/OCA/account-financial-tools/pull/1510 in commit https://github.com/OCA/account-financial-tools/pull/1510/commits/df45bac40de760f9f7f715cf2a6e70768d152ffc

**Comment by rafaelbn** [comment]
@moylop260 do you have this issue?

**Comment by moylop260** [comment]
@rafaelbn 

No, I was not aware

@RodrigoBM 
Could you fix it in v14.0 and v15.0, please?

**Comment by RodrigoBM** [comment]
@moylop260 done

**Comment by RodrigoBM** [comment]
@moylop260 close this issue, thanks

**Comment by moylop260** [comment]
Fixed from https://github.com/OCA/account-financial-tools/pull/1520 and https://github.com/OCA/account-financial-tools/pull/1521
