### ISSUE TITLE
[14.0]Question regarding  account_invoice_constraint_chronology

### ISSUE THREAD

**Issue by flotho** [OCA/account-financial-tools#1466]
Hi @alexis-via  

Hope you're doing well.
 I have a question regarding your module. I would like to know the reason why you kep the draft  invoices in your code here 
https://github.com/OCA/account-financial-tools/blob/14.0/account_invoice_constraint_chronology/model/account_move.py#L30 
I suppose that there is a use case that I'm not able to figure out so your explanation would be welcome.
Thanks in advance,

**Comment by sbidoul** [comment]
@flotho sometimes we create draft invoices at a specific date, because we know we will want to send it at that date, and in case it was not validated on time, it is useful to prevent validation of posterior invoices so we can check why the draft has not been validated.
