### ISSUE TITLE
8.0 currency_rate_update: doesn't get company_id in the method _onchange_service()

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-financial-tools#151]
With an up-to-date code from account-financial-tools/8.0, when the method _onchange_service() is executed, if self.company_id.multi_company_currency_enable is True, we have:

```
company_id = self.company_id.id
```

But, if you print this variable in the code, you have:

```
self.company_id.id= <openerp.models.NewId object at 0x7f839a8d3b50
```

So then the variable "currencies" doesn't have any values, so you can't select the currencies that needs to be dowloaded for this webservice.

**Comment by guewen** [comment]
Looks similar to https://github.com/odoo/odoo/pull/5203

**Comment by alexis-via** [comment]
Thanks for pointing out this interesting bug report.

My code of odoo is just 2 days old, and the fix for the bug on odoo has been merged 8 days ago. So it's probably another issue...

**Comment by feketemihai** [comment]
Even with that pull i think the function must be changed...looking at https://github.com/odoo/odoo/commit/2eb3ad2b460a4cbe832549c81aa71ba8614296ae
where i think it's the same...

**Comment by alexis-via** [comment]
This bug still exists with an up-to-date Odoo v8 :-(
