### ISSUE TITLE
[16.0] account_usability incorrect hierarchy of groups

### ISSUE THREAD

**Issue by remi-filament** [OCA/account-financial-tools#1558]
## Module
account_usability

## Describe the bug
When installing account_usability on v16.0, you now get hidden groups (group_account_readonly, group_account_user) in Accounting menu.
There is however a problem with hierarchy since group_account_user and group_account_manager are not related), so if you select group_account_user you will not have manager rights and Configuration menus, if you select group_account_manager you will not have accounting rights and the advanced menus (dashboard, accounting) and attached functionalities...

Using user menu, you then cannot set both group_account_user and group_account_user.

## To Reproduce
**Affected versions**: v16.0

1. Install account_usability
2. Change rights for your user : Bookkeeper --> you do not get Settings menu in Invoicing anymore
3. Change rights for your user : Accountant --> you do not get Dashboard, Accounting menus anymore

**Expected behavior**
I am not sure what should be the proper way-forward, I see 2 options : 
1. we had hierarchy between manager > user (inherit_id) (but we may have to add also hierarchy between readonly user and group_account_invoice) --> doing this we give accounting rights to all users with invoicing rights, and this may not be the expected result
2. we keep 2 separate groups : billing (manager > invoice) and accounting (user > readonly), noting that there is already hiearchy between user > invoice

**Comment by remi-filament** [comment]
Hi @legalsylvain since you added the categories when migration to v16 account_usability, can you please have a look at that issue and let me know what should be the proper way-forward from your point of view ?

**Comment by legalsylvain** [comment]
Hi @remi-filament. The objective of this module is clearly to add missing things that are present in EE and / or hidden in CE. So I try to stick with EE settings. 
you're right, something is not consistent between CE + account_usability and EE.

I chose solution 1, so. (make manager depends on user).

note : there is no dependency between readonly and invoice as in EE.

See : https://github.com/OCA/account-financial-tools/pull/1559
