### ISSUE TITLE
[15.0][16.0] account_move_name_sequence: Error to delete journal entry 

### ISSUE THREAD

**Issue by RodrigoBM** [OCA/account-financial-tools#1561]
## Module
Account Move Number Sequence (technical name: account_move_name_sequence).

## Describe the bug
When deleting an journal entry, which is associated to a journal with a sequence configured with standard implementation, it gives a code error. 

## To Reproduce
**Affected versions**:

V16:
1. Change in the sequence associated with the journal Bank (Accounting --> Configuration --> Journal --> Bank --> Entry Sequence)
    * Implementation to Standar
    * Prefix to BANK/%(range_year)s/
2. Record payment of an invoice associated with the Bank journal. (Accounting --> Customers --> Invoices (any posted) --> Register Payment --> Create payment (Journal: Bank))
3. Delete the journal entry associated with the payment. (Accounting --> Journal Entries --> Search "Bank/" --> Open any --> Reset to draft --> Action --> Delete)
4. Ger error

![Selección_143](https://user-images.githubusercontent.com/6359121/213679846-e307e613-5ba1-4a3d-907f-180c746a8580.jpg)

**Expected behavior**
Delete the journal entry

**Additional context**
Error in found in both v15 and v16

**Comment by moylop260** [comment]
Thank you for taking care about

The PR related to 16.0 will be merged soon

Question, Do you have planned to create the PR for 15.0?

**Comment by RodrigoBM** [comment]
> Thank you for taking care about
> 
> The PR related to 16.0 will be merged soon
> 
> Question, Do you have planned to create the PR for 15.0?

here it is https://github.com/OCA/account-financial-tools/pull/1566
