### ISSUE TITLE
[14.0] account_loan module can not be installed

### ISSUE THREAD

**Issue by tv-openbig** [OCA/account-financial-tools#1564]
If i open a runbot in order to test the functionality of the account_loan module it can't be installed.

## Module
account_loan

## Describe the bug
Module should normally alreday installed if i understand runboat functionality correct.

## To Reproduce
1. Open a runboat instance
2. Extend your rights by "Full accounting" group assignation to your user (admin)
3. Detect that you can't find any menu related to "loan"
4. Go to Apps menu and try to install account_loan by hand.
5. Here it stucks in status "To be installed"
![Bildschirmfoto 2023-01-24 um 17 01 54](https://user-images.githubusercontent.com/8348598/214344330-3a3a6ad8-f25c-4b70-822a-79a8d92ac9fd.png)

**Expected behavior**
In order to test the module should be installed already or it should complete the manual installation.

**Comment by tv-openbig** [comment]
On a local system installation was successful after installation of the following python packages:
numpy
numpy-financial
I have installed them by pip3 on my Ubuntu 20.04
![Bildschirmfoto 2023-01-25 um 11 40 13](https://user-images.githubusercontent.com/8348598/214542928-d0db61a1-ebf2-41a3-aa66-e8118bce03b3.png)



I am not sure if i should close the issue

**Comment by francesco-ooops** [comment]
@OCA/accounting-maintainers runboat for v14 have effectively been failling in the last month+ (no module is installed after account_loan), could you address this issue? 

Thanks!

**Comment by rafaelbn** [comment]
Please @etobella , could you help here?

**Comment by etobella** [comment]
I am reviewing it and I think I found the origin of the issue...

**Comment by flotho** [comment]
same issue with numpy version, impossible to install the requirements with 
```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
```
![image](https://user-images.githubusercontent.com/1043935/223751052-03e78936-878a-418a-bd38-fc080aa57e79.png)

changing the numpy version helps to solve the issue.
