### ISSUE TITLE
[16.0] The sequence is not set at confirmation

### ISSUE THREAD

**Issue by mourad-ehm** [OCA/account-financial-tools#1602]
## Module
account_move_name_sequence

## Describe the bug
1-When I confirm an invoice I got "The operation cannot be completed: A move can not be posted with name "/" or empty value
Check the journal sequence, please".
2-In oca runbot I got an other behaviour. There is no message but the sequence in not taken in to account.
Concerning the first case, in debug mode in my dev env, the "name" field compute are triggered  before state value changement if I change also date otherwise is not triggered by confirm action if date don't change but exception is triggered !

## To Reproduce
**16.0**:

![image](https://user-images.githubusercontent.com/15939329/222687091-2f74ca9d-5ce3-461a-80ab-e572ba521008.png)

![image](https://user-images.githubusercontent.com/15939329/222687233-fe175881-cf48-49f3-8745-817da8dc8b4e.png)

  ##1.Change sequence prefix of Customer Invoices journal  
2. create an new invoice.  
3. Compare invoice number with journal sequence definition.

**Expected behavior**
invoice number must correspond to  journal sequence definition.

**Comment by mourad-ehm** [comment]
ping @alexis-via , @moylop260 , @frahikLV , @RodrigoBM , @pedrobaeza

**Comment by RodrigoBM** [comment]
Hi @mourad-ehm 

This works fine for me on a runbot

![Selección_264](https://user-images.githubusercontent.com/6359121/224006520-ae19f9bc-f9c1-4868-8c8a-94121d2a4565.jpg)

![Selección_265](https://user-images.githubusercontent.com/6359121/224006533-ff959605-cce9-4ff2-8f01-3e424ca2bb83.jpg)

Have you done anything else?

Un saludo

**Comment by mourad-ehm** [comment]
> 
No, I didn't do anything else. I just modified the parameters of the sequence (prefix: TTT...). 
Otherwise I remarked that in my base the date range contain 2018. Is possible that someone have change some thing in database before I did the test.

**Comment by aantolkovic** [comment]
Dear all,
I have the same problems. Can you please explain me how to fix that issue. Thank you!

I change it to 16.0.2.0.0 but now have another error when I make an invoice. 
The operation cannot be completed: new row for relation "account_move" violates check constraint "account_move_name_state_diagonal"

**Comment by moylop260** [comment]
It was already fixed for lastest fixes

Please, feel free to re-open it if you still can reproduce it
