### ISSUE TITLE
V16

### ISSUE THREAD

**Issue by tompohling** [OCA/account-financial-tools#1626]
module: account_loan
version: 14.0

Hello,

Have you planned an update to version 16?

Cheers

Tom

**Comment by pedrobaeza** [comment]
Check for the v16 migration progress:

https://github.com/OCA/account-financial-tools/issues/1472

and you can consider funding any of the contributors of the module for doing such migration.

**Comment by tompohling** [comment]
account_loan is not listed yet.

**Comment by pedrobaeza** [comment]
That's because nobody had picked it for being migrated

**Comment by tompohling** [comment]
Okay, thanks.

Is there any way to trigger the migration?

**Comment by pedrobaeza** [comment]
Not sure what you mean by trigger.

**Comment by tompohling** [comment]
We want to use account_loan in V16 for our customer and the question is, when this app will be available in V16?

**Comment by pedrobaeza** [comment]
All efforts are voluntary, so if you want to speed up (or to get it) the migration, fund any of the contributors to do it.

**Comment by tompohling** [comment]
Hi Pedro,

I come back to you regarding the migration of account_loan to V16.

Our customer needs this app and wants to know how we can realize a funding to speed up the migration.

How can we fund, to which contributor and how much? Do you have any experience with that?

Cheers

Tom

**Comment by pedrobaeza** [comment]
Hi, Tom,

The logical one is to contact the author of the module (@etobella) to see if he is able to do the migration and his quotation for that. Alternatively, other developer may do the migration, but you should demand that the migration lands on OCA (through a pull request) and complies with the minimum quality checks (the red/green statuses in the pull request).
