### ISSUE TITLE
[16.0] account_usability: New Transaction-button leads to User Error instead of Transactions screen

### ISSUE THREAD

**Issue by svenv** [OCA/account-financial-tools#1651]
## Module
[account_usability](https://github.com/OCA/account-financial-tools/tree/16.0/account_usability)

## Describe the bug
The New Transaction button of a cash journal leads to a User Error instead of Transactions screen

## To Reproduce
**Affected versions**: 16.0

1. Click on the "New Transaction"-button of a cash journal on the Accounting dashboard

**Expected behavior**
Should lead to Transactions screen to add a new transaction

**Comment by rafaelbn** [comment]
@legalsylvain , please! could you review this one?

**Comment by rafaelbn** [comment]
Hello @svenv , why do you think this issue is because `account_usability` ?

`account_usability` don't modify any functionality at all

**Comment by legalsylvain** [comment]
Hi. Unrelated with account_usability.
- Open runboat. 
- Uninstall the module. 
- The error still occures.

Note : that's a normal core error in my opinion.
