### ISSUE TITLE
[16.0] account_usability: Registering payment sets status invoice as paid instead of in_payment

### ISSUE THREAD

**Issue by svenv** [OCA/account-financial-tools#1652]
The Payment Status (payment_state) of the invoice should show payment_status 'in_payment' instead of 'paid' when registering a payment. After reconciling with the bank statement, it should change to 'paid.

## Module
account_usability

## Describe the bug
Invoices with a registered payment immediately are showing status "Paid" instead of "In Payment". In default Odoo logic, customer or vendor payments are booked under the outstanding receipts / payments accounts and are then reconciled with the bank or cash statement. Only when they are reconciled, should the status of the related invoice change to "Paid".

## To Reproduce
**Affected versions**: 16.0

1. Register a payment to a customer or vendor invoice with default accounts selected
2. Invoice status will show Paid

**Expected behavior**
Invoice status should show In Payment, unless the preferred outstanding receipts / payments account is set to the account of the journal itself.

**Comment by rafaelbn** [comment]
Hello @svenv , why do you think this issue is because `account_usability` ?

`account_usability` don't modify any functionality at all

**Comment by OSevangelist** [comment]
@rafaelbn @svenv i came across that behaviour as well lately. I think what @svenv ment was stand standard Odoo EE behaviour is what he described but apparently Odoo CE code differs here. It is unclear to me why and if that was chosen deliberately or by accident. In https://github.com/OCA/bank-payment/issues/740#issuecomment-824761836 that was briefly discussed and @pedrobaeza even favoure for using the "in_payment" state (which i would as well) but nobody ever refocused on that i suppose. Does by chance anyone know a better source on why or where the final decision has been taken. Maybe @pedrobaeza or @alexis-via know the clue about it ? Any hint is very much appreciated

**Comment by pedrobaeza** [comment]
https://github.com/OCA/bank-payment/pull/1174

**Comment by OSevangelist** [comment]
Awesome @pedrobaeza that's a precise pointer. I will follow up on that then.
