### ISSUE TITLE
account_chek_deposit

### ISSUE THREAD

**Issue by Aquilog** [OCA/account-financial-tools#171]
Hello,

I coded a small improvement on your module
new field : target_amount
You can then filter checks so your remittance will reach just above this target amount
How can I share ?

**Comment by pedrobaeza** [comment]
Please make a PR against the main branch.

**Comment by Aquilog** [comment]
I'm new to github, what do you mean by PR ?

**Comment by pedrobaeza** [comment]
PR = Pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by Aquilog** [comment]
Thank you.
I'll try

_Guillaume JULLIEN_

www.aquilog.fr

Mobile  06 24 68 25 24
Fax     05 57 96 83 58
Mail    g.jullien@aquilog.fr mailto:g.jullien@aquilog.fr
Web     www.aquilog.fr http://www.aquilog.fr

**Comment by bodedra** [comment]
IMO these is ready to close.
