### ISSUE TITLE
[V12] account_assets_management:   Asset with prorated time - past date

### ISSUE THREAD

**Issue by fcvalgar** [OCA/account-financial-tools#1712]
## Module
account_assets_management

## Describe the bug
When we create an asset with a prorate option and the date is in the past, sometimes the depreciation board has a negative depreciation line that is compensated in the final depreciation extra line.

## To Reproduce
Video
https://www.loom.com/share/c6f78867594a4121b31bb28e0c135699?sid=ff5ca456-7a9b-47b5-ace2-5dd7cc54e7f9

@Moduon MT-3050

**Comment by rafaelbn** [comment]
Maybe the solution of this is https://github.com/OCA/account-financial-tools/pull/925 from @luc-demeyer
