### ISSUE TITLE
Check Deposit and its Impact in Odoo

### ISSUE THREAD

**Issue by bvdeveloper** [OCA/account-financial-tools#1796]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by pedrobaeza** [comment]
Please stop posting here things that are not issues, but another thing (and very bad explained).

**Comment by bvdeveloper** [comment]
Hello Team

I want to do the transcations for check deposit. One of my client does not want to follow the reconciliation Process inside an Odoo with the Bank statement.

Client wants to cretae the customer invoice>register payment >payment method would be check> so invoice will goes under in payment and after that want to create one check deposit where one by one payment which received through check from the customer that wants to validate or void and with the help of cleared and void want to reconcile it.

In these Case I have thought to use the check deposit module which link is here:https://apps.odoo.com/apps/modules/15.0/account_check_deposit/

As shown in these module I have done the configuration Created a one new journal as a check received and set the outstading receipts account against the payment method- Check , created a new invoice >register the payment and done the payment with these journal- check received so 

Invoice Entry is:

A/R Dr 1000
to Product sales 1000

Register payment(check Received- Journal)
Outstanding receipt Account Dr.
to A/R Account

And as shown in the module usage creating check deposit get all the checks received so at that time setting the check journal- check received and transferred bank account is setted as a bank journal which pick bank account from there after validating it
Module passes the journal entry as a check received(Journal)- outstanding receipt account to Bank(Journal)- Outstading receipt account so outstanding account would be reconciled and invoice status would be as a paid from the payment status.

These is how Module working But at the end module is not passing the journal entry in the bank which we received from the customers that needs to be developed(These is my analysis)

So at the end Entry should be Bank Account and Product sales account. 

If My analysis is wrong then please guide me how I can fulfill the requirements.

Thanks in advance

**Comment by pedrobaeza** [comment]
Please share that on the forums to get answers.
