### ISSUE TITLE
Missing context in _check_max_delta_days

### ISSUE THREAD

**Issue by Assem** [OCA/account-financial-tools#181]
Hello,

Can you please add a parameter context to the _check_max_delta_days function in currency_rate_update.py : I think it's the standard and It add flexibility.

Branch 7.0

Thkx,

Assem Bayahi

**Comment by yvaucher** [comment]
@Assem Could you do a pull request for that ?

**Comment by Assem** [comment]
https://github.com/OCA/account-financial-tools/pull/182
