### ISSUE TITLE
DISMISSIONE PARZIALE CON RILEVAZIONE MINUSVALENZA: valore residuo dentro al cespite diverso dal valore residuo sulla stampa del registro

### ISSUE THREAD

**Issue by Marianna-Marasco** [OCA/account-financial-tools#1915]
Quando si dismette parzialmente un bene e vi è minusvalenza il valore residuo visibile dentro il cespite rimasto in essere è diverso da quello che è visibile sul registro cespiti.
Succede perchè il valore della rettifica negativa, che viene sottratto dal valore ammortizzabile, include già la minusvalenza che non dovrebbe, quindi, essere più tolta.
Il valore residuo corretto è quello mostrato sul registro cespiti.

Passi per riprodurre il problema:
1) Creare fattura di vendita per un valore imponibile più basso del residuo (differenza tra valore acquisto e valore fondo ammortamento)
2) Scegliere un bene da vendere con opzione "Dismissione parziale" 
3) Indicare il valore acquisto e valore fondo ammortamento
4) Confrontare il valore residuo dentro il cespite e valore residuo nella stampa del "Registro cespiti"

**Comment by pedrobaeza** [comment]
Sorry, you have to talk here in English, and please put the module name and Odoo version. Closing meanwhile.
