### ISSUE TITLE
Odoo Currency Convertor error

### ISSUE THREAD

**Issue by VimalRughani** [OCA/account-financial-tools#207]
Hi 
I have installed Odoo from bitnami and install your latest module for currency conversation. I am generating payslips in different currency for different users. Payslips are generated properly, journal entries are generated properly, but when I check actual account, amount was not deducted properly. Currency conversation was not made properly. So I have check log of that your module and found below error. 

" 2015-05-06 10:39:53 ERROR : ValueError('could not convert string to float: helvetica',) "

Can you please help me on this, how to resolve this error.

**Comment by cunguito** [comment]
any update on this bug?
