### ISSUE TITLE
[8.0] account_chart_update taxes updating

### ISSUE THREAD

**Issue by antespi** [OCA/account-financial-tools#232]
We have detect some issues when updating Spanish Account Chart:
- If template tax has change its parent_id field, this change is not detected and then this tax is not updated
- If there is a current tax deactivated with the same description as a template tax, then wizard do not re-activate this tax nor create a new one.

We tried to resolve these issues in this PR: https://github.com/OCA/account-financial-tools/pull/231
Please review it and send your comments or approvals

**Comment by pedrobaeza** [comment]
You can put directly this issue text in the PR that solves it if you want. I see issues like a previous step if there is no PR, or the PR is going to take some time.

Also, you can put in the commit text "Closes #issue_num" to automatically close the issue when the PR will be merged

**Comment by antespi** [comment]
Ok, thank you. I'll do this way next time
