### ISSUE TITLE
Transifex password not recognized

### ISSUE THREAD

**Issue by yvaucher** [OCA/account-financial-tools#233]
Travis failed on transifex:

https://travis-ci.org/OCA/account-financial-tools/jobs/65095319

I checked on:
https://github.com/OCA/maintainer-quality-tools/issues/194

The key seems right.

@bwrsandman any idea?

**Comment by bwrsandman** [comment]
I made a mistake last week but fixed it after. https://travis-ci.org/OCA/account-financial-tools/builds/65235487
