### ISSUE TITLE
Adding the concept of asset location to an asset

### ISSUE THREAD

**Issue by saltonmassally** [OCA/account-financial-tools#304]
I think asset location needs to be added to asset... if the OCA team is in agreement I can do this and create a PR

**Comment by luc-demeyer** [comment]
If you do this, please do it in a separate module.
There is really a lot of difference between the management of financial assets versus non-financial assets a company has. Once you start adding a field like an address, the next thing is e.g. an employee using the asset, etc, etc.
Having a module in the OCA for managing company assets in general and add a link between the two would be great.

**Comment by saltonmassally** [comment]
@luc-demeyer thanks for your response... i guess I got Fixed asset and financial asset mixed up
