### ISSUE TITLE
account_move_line_search_extension Error

### ISSUE THREAD

**Issue by AizenL** [OCA/account-financial-tools#323]
Hi,  Just Installed This module and Im Receiving this error:
Odoo Version 8.0

Uncaught TypeError: viewclass is not a function
/web/js/web.assets_backend/7812b85:3143

Try it: You have to go to Accounting -- Journal Entries -- Journal Items Search All
http://111428-8-0-0ea130.runbot.odoo.com/web?db=111428-8-0-0ea130-all

**Comment by luc-demeyer** [comment]
I tried to reproduce the problem by clicking on the runbot URL but I couldn't even get into the accounting menu, hence something seems to be completely wrong with this runbot,build.
Which is the PR at the origin of this build (if any) ? Are there other ways to reproduce this problem (e.g.which combination of installed community modules is causing this problem) ?

**Comment by AizenL** [comment]
Hi, even with a base Installation this module is not working.
http://112074-8-0-7a0a64.runbot7.odoo.com/
admin:admin

The error is marking this line as invalid only when the module is activated and I click on the menu created.

var controller=new viewclass(this,this.dataset,view.view_id,options);controller.on('history_back',this,function(){var am=self.getParent();if(am&&am.trigger){return am.trigger('history_back');}});controller.on("change:title",this,function(){if(self.active_view===view_type){self.set_title(controller.get('title'));}});if(view.embedded_view){controller.set_embedded_view(view.embedded_view);}

**Comment by luc-demeyer** [comment]
I don't know how you come to this runbot build but you should have version 8.0.0.6.0 of the "account_move_line_search_extension" module whereas I see in the runbot module list as latest version "8.0.1.0".
Please make sure that you use the latest 8.0 version of this module which you can download from https://github.com/OCA/account-financial-tools/
