### ISSUE TITLE
Bug on currency_rate_update module

### ISSUE THREAD

**Issue by falinwa** [OCA/account-financial-tools#33]
Hi OCA,

I have used currency_rate_update module, it’s a great module to update currency rate automatically.

But I found a problem, sometimes we get the wrong rate.

As for your info, My database has a multicompany configuration
my first company base currency is CNY,
My second company base currency is HKD
And we choose yahoo provider to update the currency.

The problem is sometimes we get the wrong rate.

Why did this happen? Is it a bug from the module?

As my point of view, there’s no problem if we failed to has the update rate on that day, but if we get the wrong rate it’s a big problem for us.

We used this module on each our customer database, and Its very big problem if we got this wrong rate.

Is there someone that has this kind of problem?

I have check it manually on the yahoo website, and the rate is right in there.

I have look on the log, and there's no error in that day.

Is it because I run the scheduler as administrator?
and the system mistakely update the rate based on first company?
but why its not always happen? just sometimes we get the wrong date.

After all, in our other database that not have multicompany configuration.
We find a similar problem too, so I think its not because of multicompany.

**Comment by nbessi** [comment]
Hello,

Did you share your rate between company or are they separated

**Comment by falinwa** [comment]
Hi Nicolas,

They are separated, so each company have a different rate.

Thank You.

Best Regards,

Hans Yonathan

OpenERP Support

FALINWA Limited

Expert in Finance & Business Intelligence

OpenERP Partner

Website:  http://www.falinwa.com/ www.falinwa.com

**Comment by nbessi** [comment]
In this case you should create one cron for each company. Even if the
addons should support mutli company by default this behavior was not tested
in version 7

2014-09-04 3:40 GMT+02:00 falinwa notifications@github.com:

> Hi Nicolas,
> 
> They are separated, so each company have a different rate.
> 
> Thank You.
> 
> Best Regards,
> 
> Hans Yonathan
> 
> OpenERP Support
> 
> FALINWA Limited
> 
> Expert in Finance & Business Intelligence
> 
> OpenERP Partner
> 
> Website: http://www.falinwa.com/ www.falinwa.com
> 
> From: Nicolas Bessi (nbessi) [mailto:notifications@github.com]
> Sent: Wednesday, September 03, 2014 8:40 PM
> To: OCA/account-financial-tools
> Cc: falinwa
> Subject: Re: [account-financial-tools] Bug on currency_rate_update module
> (#33)
> 
> Hello,
> 
> Did you share your rate between company or are they separated
> 
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/OCA/account-financial-tools/issues/33#issuecomment-54289860>
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/account-financial-tools/issues/33#issuecomment-54393367
> .

## 

Nicolas Bessi
Senior ERP consultant
Business Solution technical manager

Camptocamp SA
PSE A
CH-1015 Lausanne

http://openerp.camptocamp.com

Direct:   +41 21 619 10 26
Office:   +41 21 619 10 10

**Comment by falinwa** [comment]
Ok, I have did it.

I will give you a feedback later for this.

But I think its not a problem, because we have other database that not have multi-company but still have the same problem.

Thank You.

Best Regards,

Hans Yonathan

OpenERP Support

FALINWA Limited

Expert in Finance & Business Intelligence

OpenERP Partner

Website:  http://www.falinwa.com/ www.falinwa.com

**Comment by AaronHForgeFlow** [comment]
Fixed.
