### ISSUE TITLE
Odoo 8 Currency Update Module - Error

### ISSUE THREAD

**Issue by tamarp** [OCA/account-financial-tools#338]
Configuration set to automatic update.
Using Bank of Canada to update USD currency but getting this error when trying to refresh currency:
ERROR : except_orm(u'Error !', u'Exchange data format error for Bank of Canada - USD !')

**Comment by ddico** [comment]
Please see #196. Hopefully it will be merged soon.

**Comment by yvaucher** [comment]
#196 has been merged
