### ISSUE TITLE
account_asset_management: tests are red

### ISSUE THREAD

**Issue by gurneyalex** [OCA/account-financial-tools#352]
the tests of account_asset_management are red. 

https://travis-ci.org/OCA/account-financial-tools/jobs/108216715#L249

**Comment by gurneyalex** [comment]
@luc-demeyer could you look into this, please?

**Comment by sbidoul** [comment]
Tests are red because we are in a bissextile year... one more day in pro-rata temporis depreciation. Funny, sort-of.

**Comment by pedrobaeza** [comment]
Is there the possibility of being fixed?

**Comment by sbidoul** [comment]
of course

**Comment by sbidoul** [comment]
Fixed by https://github.com/OCA/account-financial-tools/commit/f61268e12e7a7684d9103ff72bebe39c4785a610
