### ISSUE TITLE
Help migrating currency_rate_update to 9.0

### ISSUE THREAD

**Issue by pjmcdermott** [OCA/account-financial-tools#358]
I'm attempting to migrate `currency_rate_update` to 9.0c. I think I'm about 75% done.

The one area I am stuck on is the `_compute_multi_curr_enable` method of `res_company`.

`company_id` no longer appears to be a property of the `res.currency` model. It is not clear to me what this method is intended to indicate. Multi-currency functionality for the company is indicated by the "Allow multi currencies" setting in Accounting | Settings.

`_compute_multi_curr_enable` is used in `Currency_rate_update_service._onchange_service` to modify a currency list based on this property.

**_Any pointers?_**

Thank you

**Comment by afwanwh** [comment]
same problem here. Hopefully someone could help on this issue.

**Comment by yvaucher** [comment]
Please see https://github.com/OCA/account-financial-tools/pull/363

**Comment by yvaucher** [comment]
Ok redirected on #318 which now includes #363 

For _compute_multi_curr_enable it seems we simply removed it. Please review the PR to check if it works as expected.

I'm closing this issue
