### ISSUE TITLE
Is addon: "account_check_deposit" use correct account_id for counterpart? 

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-tools#360]
I have played around with account_check_deposit and I like it overall. But to my understanding, the counterpart move line should be using account_id form Account Journal of the selected Bank, isn't it?

Now, I see the system always use "Account for Check Deposits" from company, and ignore what ever Bank user  selected.

Am I missing something?
Thank you,

**Comment by coodec** [comment]
As I understood from the readme, that account will be used while the check hasn't been sent to the deposit and when the deposit is done, the bank account will be used.

I'd like to migrate this module to v9. Which version are you working with?
