### ISSUE TITLE
How to generate my opening entries if I alway get this error?

### ISSUE THREAD

**Issue by lapagept** [OCA/account-financial-tools#366]
Hello there,
I have account_constraints installed.  I don't find a solution to generate my opening entries in my accounting.
I always get this error. How to correct the situation?

Error :
                 _('You cannot do this on an entry generated by a bank'
                      ' statement. '
                      'You must change the related bank statement'
                      ' directly.\n%s.') % err_msg)

**Comment by pedrobaeza** [comment]
Not related to the module. It's an standard message.
