### ISSUE TITLE
account_reset_chart Integrity Error

### ISSUE THREAD

**Issue by oremacle** [OCA/account-financial-tools#374]
module: account_reset_chart
version: 8.0
- Module installed on database with Swiss account chart

**Current behavior**
Run the part of code provided 
`import erppeek

host = 'localhost'
port = '8069'
admin_pw = 'admin'
dbname = 'test'

client = erppeek.Client('http://%s:%s' % (host, port))
client.login('admin', admin_pw, dbname)
client.execute('res.company', 'reset_chart', 1)`

I've get this error
`xmlrpclib.Fault: <Fault warning -- Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by bodedra** [comment]
Due to lack of response, we can close these.
