### ISSUE TITLE
Take currency exchange rates from new Polish National Bank API (NBP)

### ISSUE THREAD

**Issue by pascon** [OCA/account-financial-tools#389]
NBP released simple Web API for taking currency exchange rates. Please update module **currency_rate_update** to take data from this more reliable source. 
Currently data from NBP is taken from released once a day xml files which need parsing. 
Web API allow to get data both in XML and JSON with easy access through HTTP GET. More information available on http://api.nbp.pl/en.html.

Thanks!

**Comment by pedrobaeza** [comment]
As this is only a request, I close as nobody has implemented it.
