### ISSUE TITLE
[v9] rates not updated

### ISSUE THREAD

**Issue by aduijs** [OCA/account-financial-tools#391]
The exchangerates i have put for USD and EUR arent updating.
- company default is set to Peruvean Sol (PEN)
- workers are running and i see the automated action "Currency Rate Update" being updated to a new day 1 day ahead.

but the log of the webservice on the  accounting -> Currency Rate -> Updatecurrency.rate.update.service,1  stays empty and the one time set exchangerate isnt changing.

am i missing something?

**Comment by aduijs** [comment]
Any idea?  Could this be because Odoo is ran by WSGI and the cron workers are runned by a "normal" odoo.py cli start up?

**Comment by pedrobaeza** [comment]
I think the problem is you haven't set base currency.
