### ISSUE TITLE
[9.0c] Add or Subtract a defined value

### ISSUE THREAD

**Issue by edser-pcg** [OCA/account-financial-tools#398]
Hello!

I've been trying to figure out how I could include in the code a subtract or add so that it could get a more favorable rate. Is there anyway I can do this?

What I mean is that the module is working fine, the only thing is that when ie. you're from Canada and go to the bank to buy USD, the rate shown in all these services is less than what you really have to pay to get that amount. So if I charge a customer USD 10,000.00, Odoo has a rate of 1.27 CAD so I'm supposed to pay CAD 12,700.00 for this amount, however the reality is that the bank is selling the USD at 1.3 so I would be having to pay CAD 13,000.00 and losing CAD 300.

**Comment by elicoidal** [comment]
@edsersolis 
Thanks for your interest in OCA modules
Which module are you refering to?
Usually in Odoo, difference is manually booked during reconciliation either in bank charge or FX exchange difference account. Meaning you book the 13000 in your bank statement and match it with 12700 with a write-off

**Comment by edser-pcg** [comment]
Hello Eric, thanks fpr your reply. The module is currency_rate_update.

Yes but the thing is that, some users don't know much accounting and others
would like to get that value automatically when applying a payment to an
invoice.

Atentamente,

Edser G. Solís

Ingeniero en Tecnologías de la Información y Comunicación | MDETI(c)

Móvil: 829.920.2009

: : Mensaje enviado desde dispositivo móvil. : :

**Comment by elicoidal** [comment]
this module is only about updating the currency rate automatically and your question is not related to its usage.
The question you have seems a general one for standard Odoo. I would suggest that you check the documentation (https://www.odoo.com/documentation/user/9.0/accounting.html) or the user forum (https://help.odoo.com).
In the meantime, I will close this issue. If you think it should be reopen do not hesitate to post a comment
