### ISSUE TITLE
Fix for currence rates - 8.0

### ISSUE THREAD

**Issue by rosenvladimirov** [OCA/account-financial-tools#409]
I made a few fixes to the modules currence rate update (date) . If there iteresnite please make them in this repository. https://github.com/rosenvladimirov/oca-patches.git

**Comment by mustafat** [comment]
How XML?

**Comment by rosenvladimirov** [comment]
https://github.com/rosenvladimirov/odoo-patches.git

**Comment by pedrobaeza** [comment]
Please propose them as a PR
