### ISSUE TITLE
Rounding Error

### ISSUE THREAD

**Issue by adamrumjahn** [OCA/account-financial-tools#414]
I believe this is a bug:

My base currency is Colombian Pesos.  
I installed the module and chose Yahoo Finance as the Webservice and added USD.

Currently the exchange rate is 0.00341USD per COP (2932COP/USD).  
However, when I update, it sets the currency to 0.000300 (3333.33COP per USD).

This obviously creates a big difference with the rounding errors, especially when we are dealing with currencies that have multitudes of differences than the USD.  For example, the Japanese Yen or the Vietnamese Dong.  

Is there a way that this can be fixed?  Is this only related to the Yahoo Finance webservice? I wasn't able to get updates from other webservices.

**Comment by adamrumjahn** [comment]
I forgot to mention, I already set the Price Accuracy accordingly

Price Accuracy
Rounding Factor
0.000001
Decimal Places
6

It still rounds to 4 decimal places, ie/ 0.000341 will still be 0.000300.  I checked online on Yahoo Finance and it does indeed state that the current rate is 0.000341.  So something is being lost in translation here.

**Comment by damendieta** [comment]
This is not the place for this, you should ask for help on the correct chanels, like stackoverflow or odoo forum. This Issue should be closed.

But: I think your problem is the accuracy on the currency, not the price, as Odoo will round on your currency accuracy.

**Comment by adamrumjahn** [comment]
@damendieta I'm not exactly asking for help, I'm reporting a suspected bug.  This is not a rounding issue, but a rounding error.  When I set 6 decimal places it still rounds as it if were 4 decimal places.  this has adverse effects on the accounting if rounded incorrectly.  As I mentioned, I have only noticed it when it updates from Yahoo Finance.
