### ISSUE TITLE
account_auto_fy_sequence: error when running on multicompany scenario

### ISSUE THREAD

**Issue by CAGIGAL-Computer** [OCA/account-financial-tools#431]
Hi I have one multicompany scenario running OpenERP 7, then I have many sequences for Sales Order, one per company, so when a user wants to create a new Sales Order the system raises an error:

```
The system tried to access a fiscal year sequence but there is more than one sequence to choose from.
```

I think is because the module will find more than 1 ir.sequences that have a sequence type = 'sales.order': one per company.

**Comment by pedrobaeza** [comment]
Your problem is because you are accessing through admin, which shouldn't be done in multi-company (not only for this).
