### ISSUE TITLE
[9.0] currency_rate_update failed update rate

### ISSUE THREAD

**Issue by davidwul** [OCA/account-financial-tools#437]
I installed the currency_rate_update module on some database in v9. But each time I tried to update, there is nothing happening. I tried with Admin.ch and yahoo. On fresh database or migrated db. 
What can I provide ?

Here is what I see from the console: 

"POST /web/dataset/call_kw/res.currency/read HTTP/1.1" 200 -

But there is no new rate available.

**Comment by adrienpeiffer** [comment]
Hello,

I just tested this one on [runbot](http://3292251-9-0-e68712.runbot2.odoo-community.org/) and it works as expected. Perheps you miss to check the flag 
_Automatic Update_ in the company's settings.
I'll close this one. Don't hesitate to reopen it if necessary.
