### ISSUE TITLE
[8.0] journal_id constraint problem on object save

### ISSUE THREAD

**Issue by 2zx** [OCA/account-financial-tools#438]
@api.constrains('journal_id') and related method _check_different_journal seems to be defined on class AccountMoveTemplateLine instead of AccountMoveTemplate

**Comment by pedrobaeza** [comment]
Can you provide the patch as a PR?

**Comment by 2zx** [comment]
Pull request created

**Comment by pedrobaeza** [comment]
Closing as the PR is already merged.
