### ISSUE TITLE
Parent chart of accounts like v8/v7

### ISSUE THREAD

**Issue by mileo** [OCA/account-financial-tools#463]
Hi, 

I found an module that include v8 parent concept in account chart 

https://github.com/steigendit/addons-steigend/tree/master/account_parent

I can filter this branch and propose it to this repo if are any interest.

>  This module will be very useful for those who are still using v7/v8 because of the no parent account and chart of account heirarchy view in the latest versions
> * Adds parent account in account
>  * Adds new type 'view' in account type
>  * Adds Chart of account heirachy view
>  * Adds credit, debit and balance in account
>  * Shows chart of account based on the date and target moves we have selected - Need to set the group show chart of account structure to view the chart of account heirarchy. - If no parent account is set, then just a list view with credit,debit, balance will be showed

Best regards

**Comment by pedrobaeza** [comment]
I prefer to have hierarchy on reports, not on data model.

**Comment by mileo** [comment]
In Brazil, we need to relate the company's chart of accounts to the government's default chart of accounts, which has parent accounts.

And periodically send a file with the relationships between the plans and the accounting entries.

![image](https://cloud.githubusercontent.com/assets/1975978/24053553/2ee58064-0b18-11e7-9bbd-f04a6f265f58.png)

More info: http://sped.rfb.gov.br/estatico/A8/2A167D61FEA613FD20E7E9BA101989F299E2F2/Manual_de_Orienta%C3%A7%C3%A3o_da_ECD_2016_Maio.pdf

**Comment by pedrobaeza** [comment]
OK, I think you can include the full hierarchy in a report with a fixed structure, but I recommend you to not mix with account.account model for avoiding the performance and functional problems.

**Comment by Danisan** [comment]
Is the performance actually affected significantly by the addition of this feature? Because I can see that is a good to have (almost a must-have).
I had several objections in the implementation of Odoo9 and 10 because of lack of this feature. Mean in Chile and Argentina, Especially when the decision is based on the opinion of professional accountants.
Pedro, is there a good report already implemented, which make up for this feature?

**Comment by pedrobaeza** [comment]
You can check https://github.com/OCA/l10n-spain/pull/480 to see if it fits.

**Comment by kittiu** [comment]
The accounting hierarchy report is also needed in our country. The implementation in Spain is quite interesting as it make sure the core feature is not touched (and as my limited knowledge goes, we only need hierarchy for reporting).
This l10n_es_account_hierarchy_report seem to be generic enough to be out of localization, is it not?

**Comment by pedrobaeza** [comment]
@kittiu yeah, that module can have a generic part outside OCA/l10n-spain and then let data only in the localization module. Anyway, please check current Odoo PRs as they are introducing for v11 again a hierarchy in community based on a new model account.group. I can't find the exact number, but we should stick to the same scheme for easing the migration.

**Comment by mileo** [comment]
@kittiu 

https://github.com/odoo-dev/odoo/blob/master-account-hierarchy-jov/addons/account/models/account.py#L201

cc @aricaldeira

**Comment by pedrobaeza** [comment]
Thanks for the pointer, @mileo

**Comment by mileo** [comment]
Please see our comment at: https://github.com/odoo-dev/odoo/commit/bfa76a1789cde0aebdd779c881f7de6a2e0c9edf
