### ISSUE TITLE
partner_daytopay

### ISSUE THREAD

**Issue by max3903** [OCA/account-financial-tools#475]
At @ursais, we have a module to compute some financial statistics for a partner:

* Average number of days to get customer invoices paid (in the current year)
* Average number of days to get customer invoices paid (lifetime)
* Average number of days to pay vendor bills (in the current year)
* Average number of days to pay vendor bills (lifetime)

I think this repository would be the best fit to host it, unless the feature already exists in a module I haven't found.

Any opinion? Interest?

Thanks.

https://github.com/OCA/account-invoice-reporting/issues/52

**Comment by JordiBForgeFlow** [comment]
:+1: I think that this would be a good contribution!

**Comment by pedrobaeza** [comment]
@jbeficent I don't agree that this is the best place. The best place is account-financial-reporting. Reporting is not only PDF or any format output. Reporting is also BI inside Odoo.
