### ISSUE TITLE
[10.0] Want to propose a module that allow Bigger / Smaller currency rate option

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-tools#476]
We have a module, it allow to use rate Bigger/Smaller when reference to Base Currency, so that we can always use rate > 1, instead of 0.0001 which can lead to digit inaccuracy. 
Here is the module we did in v8
https://github.com/pabi2/pb2_generic/blob/master/res_currency_rate_ext

Want ask if there is already similar module in community. If not yet, is this module good to be in OCA?

**Comment by elicoidal** [comment]
Please check: https://github.com/OCA/account-financial-tools/pull/337
I would suggest you collaborate to make this PR merged.

**Comment by kittiu** [comment]
@elicoidal @jbeficent 

I tried checking out the issue #337. It is a nice and simple approach. But as it is using the **1/rate**, it just won't compatible with the **currency_rate_update**, which is updating into **rate** field. (Otherwise we need to modify and the currency_rate_update to accept invert flag)

Our approach is a bit different. By providing, a new field **rate_input** for user to key in, then make **rate** a computed field (base on bigger and smaller) and use it as it should (we can make it inverse compute fields too, and **currency_rate_update** can update rate).

This way, user can fill rate_input as provided by bank, i.e., given USD > THB > JPY.
- THB <-> USD = 37.0 (rate = 37.0 as used by Odoo)
- THB <-> JPY = 3 (rate will become 0.3333333 as used by Odoo)

I see no other way yet, if we consider the currency_rate_update. What do you think?

Note: I also read #335, but not sure how it goes now.

![229](https://cloud.githubusercontent.com/assets/1973598/25520833/9b39293e-2c27-11e7-9234-712a9655c3e9.png)

![228](https://cloud.githubusercontent.com/assets/1973598/25520834/9de08f88-2c27-11e7-8f49-80c0347667be.png)

**Comment by elicoidal** [comment]
@kittiu I am personally comfortable with the original implementation which IMHO covers most potential business cases but I agree the currency_rate_update is a good point.
@jbeficent: your thoughts?

**Comment by andhit-r** [comment]
Hi @kittiu, i also need implementation of currency exchange method (direct/indirect). My #335 obviously not a proper way to go. @jbeficent #337 is the most proper way to go. 

I already use #337 on out production (https://github.com/open-synergy/account-financial-tools/tree/8.0-dev). But the implementation also raise issue with account_multicurrency_revaluation. So i have to tweak that module (5eef301c19caae9989f12384800607c473b91c7f). It seems that if we want to proceed with #337 we need to create a glue module. I never use currency_rate_update so i could not give you any suggestion. But i guess the problem will be similar with problem i encounter on account_multicurrency_revaluation. Other then that i haven't encounter other issue.

Please inform me if you would like to proceed, we might be able to collaborate.

**Comment by kittiu** [comment]
Hi @andhit-r 
Personally I also like the simplicity for what @jbeficent has proposed. While waiting, I also though the same about glue module.
But I am not sure how OCA coding standard will welcome the glue module. Meaning, if user want to use both currency_update and currency inverted, he/she need this knowledge to install manually the glue one, right? Or there is other mechanism to warn user?
@elicoidal @jbeficent WDYT?
If it is ok, I can help writing the glue one with your help to review it, or vice versa. So, we can close the much needed module #337.

**Comment by andhit-r** [comment]
@kittiu that's when auto_install comes to the rescue. Gule module will have auto_install == True. So when user install bot currency invert and currency update glue module will be automatically installed.

**Comment by kittiu** [comment]
@andhit-r auto_install can be triggered based what other has installed?

**Comment by andhit-r** [comment]
Yes suppose that the glue module has currency_invert and currency_update as dependencies. And it has auto_install == True. As soon as user installed both currency_invert and currency_update, odoo will automatically install the glue module.

Although automatic install will not apply in these scenario:

* User already install currency_update
* currency_invert merge
* User install currency_invert
* glue module merge

Odoo will not install glue module automatically. So i guess we have to propose both currency_invert and all glue module on same PR. And those modules has to be merge at the same time.

**Comment by kittiu** [comment]
@andhit-r thanks for all the input. I think I almost ready to start with your glue module. Just another one point. I saw you mentioned that, beside currency_rate_update, you also fact the same problem with account_multicurrency_revaluation, right? So, we will need the glue module for it as well?

Beside these two, if any other module in the future make use of field **rate**, we would need a glue module for each of them? 

If that, so, that could be the show stopper, isn't it? Appreciate your valuable opinion on this matter.

**Comment by gustavovalverde** [comment]
What happened with this subject?

**Comment by kittiu** [comment]
@gustavovalverde we are waiting for the decision from the experienced person, I believe. At the end this kind module is needed either way.
Do you have comment?

**Comment by kittiu** [comment]
@elicoidal do you think we should reopen this issue?

**Comment by elicoidal** [comment]
@kittiu If you can find a use case not covered by original implementation/module, please reopen it. 

The idea of glue module is a simple way to solve some of your request.
