### ISSUE TITLE
Missing ACL on credit.control.dunning.fees.computer

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-tools#49]
While investigating why travis was red on #48, it appeared it is due to a missing ACL on credit.control.dunning.fees.computer (in module account_credit_control_dunning_fees).
https://travis-ci.org/OCA/account-financial-tools/jobs/36345695

I started to add it when I noticed it was a bit of a special Model. At first glance I had the impression that it could be modified to be a TransientModel (which would lift the issue of the ACL), but I don't fully understand why it is built this way.

So I pass the ball.

**Comment by nbessi** [comment]
Done here https://github.com/OCA/account-financial-tools/pull/60
