### ISSUE TITLE
[10.0][account_credit_control] Menu entries not shown on Runbot

### ISSUE THREAD

**Issue by matteotrubini** [OCA/account-financial-tools#523]
REF: https://runbot.odoo-community.org/runbot/92/10.0

I didn't found any menu entry even on a test installation from scratch.

**Comment by ausl** [comment]
I am having the same issue

**Comment by cubells** [comment]
You must activate correct permission for your user:

![seleccio_315](https://user-images.githubusercontent.com/4386443/29375120-32ae9f78-82b4-11e7-9661-16d6f86d675f.png)

Issue can be closed.
