### ISSUE TITLE
Need to check "Allow Reconciliation" for the account in the journal "Check Received"

### ISSUE THREAD

**Issue by LoanHuynh** [OCA/account-financial-tools#540]
module: account_check_deposit
version: 9.0

**Steps to reproduce**
- Make payment for a customer invoice by "Check received"
- Create a Check deposit:
   + Journal: Check received"
   + Account: account on the company form view.
   + Table "Check payment": add the payment line used in the invoice above.
- Validate that check deposit.

**Current behavior**
- A message "The account Check Received (512004) is not marked as reconciliable !" when trying to validate the check deposit.
- When I go to that account and active the checkbox "Allow Reconciliation", I got another message "You cannot change the value of the reconciliation on this account as it already has some moves"

**Expected behavior**
- Allow to validate that deposit

**Solution**
- By default, we should check "Allow Reconciliation" for that account when installing the module.

**Comment by DonFeraRRi** [comment]
Any Solution if we have entered the values and now I am unable to Allow Reconciliation. 
A message "The account Other Debtors (2006) is not marked as reconcilable !"

When I go to that account and active the checkbox "Allow Reconciliation", I got another message "You cannot change the value of the reconciliation on this account as it already has some moves"

Any way to do something? I tried to export the account Moves and Change the account to a dummy account and then Allowing Reconcilation on that account. but in that Case as I imported the CSV file with new Dummy Account ID, I am getting this validation. "You cannot do this modification on a posted journal entry, you can just change some non legal fields. You must revert the journal entry to cancel it. Move name (id): VBPN18259 (10511). at row 196
Resolve other errors first

Anything that I could do here?

**Comment by AbrahamMatu** [comment]
Having the same issue. Any  solutions?

**Comment by fclementic2c** [comment]
And it is not only in this specific case.
I do not get why odoo prevent to check this box when account_move_line have been created.
I usually use SQL to check it and I never noticed any issues.

this is really a pain and it is there on all odoo version since version 9

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/account-reconcile/tree/11.0/account_set_reconcilable module for allowing to change it. The logic after not allowing this is because it will appear a lot of moves to be reconciled in the bank statement.

**Comment by fclementic2c** [comment]
Many thanks @pedrobaeza . I missed that one.
