### ISSUE TITLE
currency_rate_update shoud support common rates (company = False)

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/account-financial-tools#546]
It should be possible to update the currency rates independently of companies.
For example if you have many companies in EUR and you want to update EUR/USD every morning, You may expect every companies to have the same EUR/USD rate.
The way it's done now (loop in companies) might end up in small exchange rates differences.
It sould be spossible to update the currency itself and not every company/currency and finally have the rates company_id field set to False ("common rate").

**Comment by pedrobaeza** [comment]
Can you provide a PR with this change?
