### ISSUE TITLE
[10.0] account_credit_control too much attachments in emails

### ISSUE THREAD

**Issue by paulius-sladkevicius** [OCA/account-financial-tools#559]
I've tested it on the runbot.

1. Create few invoices with different customers
2. Run credit control
3. Select all credit control lines for sending out by email
4. Select all credit control lines and send them by email

**Result excepted**: To get credit control summary attachment per email
**Result observed**: Second email gets attachment from previous credit control lines based on a sequence of emails creation. E.g. if there is 5 credit control lines, 5 line will get totally 5 attachments.

Any ideas?

![more_attachments](https://user-images.githubusercontent.com/213811/31678138-d60af314-b375-11e7-99f1-89a59959193e.png)

**Comment by adrienpeiffer** [comment]
@paulius-sladkevicius Can you put the link to the runbot build ?

**Comment by paulius-sladkevicius** [comment]
@adrienpeiffer http://3306955-10-0-ba5e61.runbot3.odoo-community.org/web?debug=1#id=6&view_type=form&model=mail.mail&action=87

**Comment by adrienpeiffer** [comment]
@paulius-sladkevicius Thanks for the report :smile: 
I just proposed a fix to solve this issue in https://github.com/OCA/account-financial-tools/pull/560. 
Once the buildbot build is complete, you'll be able to test it direclty with the runbot link in the bottom of the PR. (https://runbot.odoo-community.org/runbot/build/3307477)
