### ISSUE TITLE
extension of  Account Invoice Constraint Chronology App

### ISSUE THREAD

**Issue by ccandito** [OCA/account-financial-tools#562]
Dear All,
for the time being this check is active for sales journal only.
It will be very useful to extend this feature to every king of journals.
Regards
claudio candito

**Comment by ccandito** [comment]
Dear All, 
do you have any news about that?
it is important to be extended to purchase invoices also.
Regards
claudio

**Comment by sbidoul** [comment]
@ccandito the module already works with purchase journals.

Do you need it for bank or misc operations journals too?

**Comment by ccandito** [comment]
Thanks
I'll test it again.
Sorry for wasting your time
Regards
Claudio candito

Il 4 gen 2018 18:29, "Stéphane Bidoul (ACSONE)" <notifications@github.com>
ha scritto:

**Comment by ccandito** [comment]
Dear Stéphane,
Finally I've tested the Account Invoice Constraint Chronology App.
currently the document date, i.e. bill date, is taken into account as reference for for chronology check.
From my perspective, this is wrong because the accounting data should be considered instead because invoices are sorted in VAT registry through the accounting date.
Regards
claudio candito

**Comment by ccandito** [comment]
Dear Stephane,
do you have any news on it.
In case it is not possible to change the implemented logic, I'd suggest to enhance it by adding the possibility to select the date field (accounting date or document date) to be taken into account.
this selection field should be place at Journal level close to the already existing "Check chronology" indicator.
Regards
claudio
