### ISSUE TITLE
account_credit_control does send mail with attachments of other credit control lines

### ISSUE THREAD

**Issue by wpichler** [OCA/account-financial-tools#565]
I've you select more than one credit.control.line and execute credit_control_emailer wizard, then the first entry will generate an email with one attachment, the second entrie will generate an email with the first attachment + the second attachment aso.

You can imagine how funny this was for the customer...

I assume this bug does affect all versions

**Comment by adrienpeiffer** [comment]
@wpichler Can you tell me on which version the problem appears ? Did you notice this behavior on runbot ?
We fixed https://github.com/OCA/account-financial-tools/issues/559 for the 10.0 version on the following revision https://github.com/OCA/account-financial-tools/commit/8d29880b71c2718b96a8149dc5408a6120cf22eb and it was backported to 9.0 on this revision https://github.com/OCA/account-financial-tools/commit/1b7f033bca819d9310cc4015e9baa9773e0cc61b

**Comment by wpichler** [comment]
I have seen this now - i've done the same patch ;-)

Thanks - so this can get closed
