### ISSUE TITLE
currency_rate_update

### ISSUE THREAD

**Issue by pierromanu** [OCA/account-financial-tools#585]
I get the following message with Yahoo Finance : 2017-11-27 11:12:32 ERROR: ValueError('could not convert string to float: the service is being discontinued.  For all future markets and equities data research',)

Unfortunately, I can't use another provider because they don't support XPF currency whereas Yahoo Finance does.

**Comment by yvaucher** [comment]
@pierromanu Yahoo Finance stop their service, we can't do anything about that.

You may look for an other provider, maybe XPF is supported by googleapis. Anyway cannot help you much on this, this needs a further development. Odoo had the same issue with their enterprise module: https://twitter.com/Frederic_C2C/status/938057417287454720

@OCA/accounting-maintainers any plan on this?

**Comment by pedrobaeza** [comment]
That source is no more valid. Use another existing source.
