### ISSUE TITLE
Missing account.journal Accounting Dashboard

### ISSUE THREAD

**Issue by xabispacebiker** [OCA/account-financial-tools#604]
Hello,

On a fresh OCA 11 installation I am missing the Accounting Dashboard link. When the initial action for the user is set to Accounting Dashboard, then the user can access it but there is no link available form the menus. Is there any option to activate it or am i missing something?

Thanks in advance

**Comment by pedrobaeza** [comment]
This has nothing to do with this repository. Report it to #odoo.
