### ISSUE TITLE
account_check_deposit counter-parts left as draft

### ISSUE THREAD

**Issue by travish2** [OCA/account-financial-tools#614]
Tested on Odoo 10 Community

The counter-part journal entry is left as a draft move and need to be manually confirmed, otherwise the general ledger is off. Is this expected behaviour? If so the instructions should updated to include periodically posting those transactions.

![image](https://user-images.githubusercontent.com/30615274/36237717-bfd30aba-1251-11e8-97d1-3d78024ba4ef.png)

![image](https://user-images.githubusercontent.com/30615274/36237766-1a931b66-1252-11e8-9184-a41a1c5740e9.png)

**Comment by alexis-via** [comment]
There is a configuration parameter "Post Move for Check Deposits" on the Accounting configuration page... check this option and the generated move will be automatically posted.
