### ISSUE TITLE
Conflict in demo data between account_group_menu and account_tag_menu.

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-tools#634]
@feketemihai see https://travis-ci.org/OCA/account-financial-tools/jobs/354341620#L1080
The demo data is duplicated. Can you change the demo data or introduce dependencies between the two modules to keep just 1 demo data?

**Comment by feketemihai** [comment]
In a few minutes..

**Comment by feketemihai** [comment]
@jbeficent Fixed in #635.

**Comment by pedrobaeza** [comment]
Closing as there's now a PR.
