### ISSUE TITLE
[RFC] porting account_tax_analysis to v9+

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-tools#649]
We are considering the migration of account_tax_analysis from 8.0 to 9.0+

That module was hugely appreciated by accountants because it enabled them to do very flexible free analysis of tax/account/partner combinations.

Since v9, this module has been replaced by account_tax_balance which is helpful too, but does not offer the same freedom of analysis. It is also quite easy to do tax reports with mis_builder, but these too do not allow free form analysis like account_tax_analysis did.  (this is direct feedback from accountants)

Migration of account_tax_analysis is not immediate mainly because the tax_ids field on account move line is now a one2many on which it is not possible to perform a group by.

So I'm contemplating a solution to add a stored computed field on account.move.line (tax_group_id or something) on which it is possible to do a group by. These tax groups would be generated automatically when updating the tax_ids field.

Thoughts?

**Comment by pedrobaeza** [comment]
But how are you going to handle if something has more than one group?

**Comment by sbidoul** [comment]
It would go as follow:

- when writing a move line with taxes A and B, create group G1, named "A, B"
- when writing a move line with taxes A and C, create group G2, named "A, C"
- when writing a move line with taxes B and A, reuse group G1
- etc

The combinations of possible taxes is quite limited (in most cases it's only one tax), so the list of groups should remain reasonable.

**Comment by pedrobaeza** [comment]
OK, it can be a good addition.

**Comment by fclementic2c** [comment]
@sbidoul Thanks for the idea. I like your approach.

There is another point which is annoying now.
You cannot jump to invoice from the move lines. The link is from invoice to move line now.
It was handy before to have the overview by taxes, then the drill down (move lines by date, account, taxes...) then once you find an error for ex. go directly to the origin document (ex: invoice) to maybe amend it.
Not sure you can do anything but I just mention it in case you have an idea :)

**Comment by sbidoul** [comment]
The tax group mechanism I explained above is complex to implement for little benefit (ie translation). So let's start with a simple text field.

So, let's add a stored computed text field named "Analysis Tax" which contains either `tax_line_id.description` or `', '.join(sorted(tax_ids.mapped('description')))`, whichever is set.

Then we need a new view on move lines, with a menu entry named 'Tax Analysis` (next to the `Tax Balance` menu entry from account_tax_balance module). It should have more or less the same columns as the [one we had in v8](https://github.com/OCA/account-financial-tools/blob/8.0/account_tax_analysis/account_tax_analysis_view.xml). @fclementic2c if you have suggestions to improve the columns to display in this view, now is the time to speak :)
