### ISSUE TITLE
[9.0] account_chart_update: Updating fiscal positions with same name launches an exception

### ISSUE THREAD

**Issue by MouTio** [OCA/account-financial-tools#650]
If you have more than one fiscal position with the same name, updating fiscal positions launches an exception and Odoo crashes.

**Comment by pedrobaeza** [comment]
Yeah, that's something that shouldn't happen, as having the same name is not the normal thing. Any way, you know the usual procedure (PR :wink: )

**Comment by MouTio** [comment]
Done.

https://github.com/OCA/account-financial-tools/pull/651

**Comment by pedrobaeza** [comment]
Closing this then.
