### ISSUE TITLE
11.0 branch build failing

### ISSUE THREAD

**Issue by guewen** [OCA/account-financial-tools#654]
After the merge of https://github.com/OCA/account-financial-tools/pull/607 the build on 11.0 is failing.
The PR was green, but meanwhile a commit in odoo / OCB introduced a change incompatible with the tests: https://github.com/OCA/OCB/commit/0e881fcd3a5671c4fe84b2a47c9d3611e4b823a1 (found by @grindtildeath)

Travis logs: https://travis-ci.org/OCA/account-financial-tools/jobs/380154983

**Comment by pedrobaeza** [comment]
You have to make the change of the currency via SQL. See one of my commits for amending this in 10.0: https://github.com/OCA/account-financial-tools/commit/ae3143b6ae18c49145b5cec5569382986b8a6590

**Comment by pedrobaeza** [comment]
You can even cherry-pick the one for this module: https://github.com/OCA/account-financial-tools/commit/76cea528b57e5bfd809bbed15be5cbf591b30f27

**Comment by guewen** [comment]
Hey so cool! Giving a try right now. Thanks
