### ISSUE TITLE
[11.0][account_loan] Extra principal payment is improperly reflected

### ISSUE THREAD

**Issue by spacimek** [OCA/account-financial-tools#668]
How to reproduce:
1) Create a loan, which will start in the future and post it
2) Click on Pay Amount - and enter some amount to be paid
3) While principal is properly lowered, the same amount is counted also towards the interest payment and system shows double-payment.
I.e. when you set to pay $30k extra, system shows: 
Total payed amount | $ 60,000.00
Total interests payed | $ 30,000.00

Same situation is in amortization schedule. You can see it in Runbot under ACL000004 loan.

**Comment by D0nmoses** [comment]
I've come to observe the same issue. Any luck so far?
