### ISSUE TITLE
[IMP][11.0][account_loan] Adding fees, insurance and tax to the loan

### ISSUE THREAD

**Issue by spacimek** [OCA/account-financial-tools#673]
While the account_loan nicely calculates the loan itself, the only place it allows to add any type of additional fee is "Pay amount" button (i.e. paying an extra amount towards the principal). In that case we can add bank fees. 

However loan management should add fee(s), insurance and tax to the monthly amount - those should be defined as extra products and added to the invoice automatically when the invoice is generated for the next period (because they can change during the course of the loan). Also they have different accounts in Accounting than the loan itself.

**Comment by etobella** [comment]
Taxes are added automatically according to the leasing product configuration.
About the fees and insurances, It could be an option to add this kind of configurations. You could make a PR in order to make these improvements.

**Comment by paoazar** [comment]
Hi, Is it possible to add some fees, insurances and taxes?
Thank you.

**Comment by cvinh** [comment]
I did a PR with Claude here https://github.com/OCA/account-financial-tools/pull/2302
