### ISSUE TITLE
Differences between account_check_deposit and account_check_printing

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#676]
Can anyone tell me the differences between this OCA module and the corresponding Odoo one? Are both needed? I have the feeling that the OCA one is not needed anymore since the improvements on Odoo side + account_check_printing_report_base.

cc @jbeficent @alexis-via @bguillot @chafique-delli @mourad-ehm

**Comment by alexis-via** [comment]
I guess account_check_printing is designed to pay your suppliers by check. The module account_check_deposit is designed to deposit the check of your customers to the bank.

**Comment by pedrobaeza** [comment]
But `account_check_deposit` also has an option for transferring the balance to the bank account. That's why I see some overlapping.

**Comment by pedrobaeza** [comment]
OK, I'm going to migrate as is for going fast with this for the customer I'm migrating. Thanks for the answer, Alexis.
