### ISSUE TITLE
[11.0 ][account_credit_control] Multicompany bugs

### ISSUE THREAD

**Issue by yung-wang** [OCA/account-financial-tools#691]
Unable to create multiple credit control runs on the same date.

1. As a multicompany user, you can view all the runs for all the companies. When you try to create another run on the same date, the system will raise the error that there already exist one on that date.
I tried to put multiple Policies from different companies into 1 run, but it will only generates the lines from the company that you're logged in. That is ok.
2. Also the view Credit Control Lines is not filtering the lines to show only the lines from the logged in company.

Please have a look if this can be fixed.

**Comment by astirpe** [comment]
I think this issue is fixed by PR https://github.com/OCA/account-financial-tools/pull/435 for 8.0.
That PR should be ported to 11.0.

**Comment by pedrobaeza** [comment]
We already added multi-company support in #695, so closing this.

**Comment by yung-wang** [comment]
@pedrobaeza Thanks, I checked #695 and it is a nice improvement.
Can we reopen the issue? Because I think it makes more sense to add a multi company rule on credit_control_policy:

```
    <record id="credit_control_policy_multi_company_rule" model="ir.rule">
        <field name="name">Credit Control Policy multi-company</field>
        <field name="model_id" ref="model_credit_control_policy"/>
        <field eval="True" name="global"/>
        <field name="domain_force">['|',('company_id','=',False),('company_id','child_of',[user.company_id.id])]</field>
    </record>
```

The reason is when you create a run, you can select all the policies from all the companies. But when you run it, it just only creates the credit control lines of the company that you're logged into. So it's not useful to see every policy from other companies.

**Comment by pedrobaeza** [comment]
Then please create a PR adding that rule.
