### ISSUE TITLE
11.0 account_asset_management: cant create asset

### ISSUE THREAD

**Issue by ghost** [OCA/account-financial-tools#730]
I try to test this module.
To create a asset you have to fill the field "parent asset". by creating the parent asset you have to fill the field "parent asset" ...  so its a loop.

Any hint how i can create assets without this loop?

Thanks.

**Comment by darmaa** [comment]
you must select asset type 'view'

**Comment by luc-demeyer** [comment]
You should first define the 'reporting structure' (assets of type view).
For some countries there can be a legal reporting structure which makes this definition easy (installation of a data module, cf. https://github.com/luc-demeyer/noviat-apps/tree/10.0/l10n_be_asset_management_data).

But I agree that the behaviour is confusing. Fixing this is on my list for the 12.0 version of this module (replacement of 'view' assets by reporting tags).

**Comment by ghost** [comment]
ok thanks to all for explanation !

I m looking forward to your 12.0 Version.
A Wishlist for this module :-)
* Possiblity to link to the Asset-Invoice like in the account_asset-module.
* A Image Field

Generell i dont know how its possible to handle Attachments in 12.0 in a good way. In the 11.0 module (asset_account) i attached a lot of documents related to the asset. In 12.0 this record have no chatter so its no possibility to attach documents (this is a general problem of 12.0. i hope it gives a generell solution)
