### ISSUE TITLE
account_asset_management - init flag based mechanism to review

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-financial-tools#731]
In my use case, Fiscal Year start on the 1/01/N but I want the depreciation computed from 01/10/N.

![image](https://user-images.githubusercontent.com/5735158/48355840-347e2d00-e695-11e8-9c06-a20161042b53.png)

But when I compute the asset depreciation board : 
![image](https://user-images.githubusercontent.com/5735158/48355866-45c73980-e695-11e8-9a65-49a34190bf1c.png)

![screenshot-integration roctool odoo camptocamp fr-2018 11 08-13-51-06 1](https://user-images.githubusercontent.com/5735158/48355883-4fe93800-e695-11e8-8248-6779a1320017.png)

I would have expect that all depreciation lines be flagged 'init' 'til Sept-18 then no flag 'til the end....

**Comment by fclementic2c** [comment]
My suggestion is to add a depreciation start date in the accounting settings like Odoo did it for bank reconciliation lines. 
![screenshot-397274-12-0-6f9e74 runbot16 odoo com-2018 11 12-16-15-39](https://user-images.githubusercontent.com/5735158/48356305-40b6ba00-e696-11e8-9073-ff2a7160507b.png)

It will be use only once at the module install but it is easier to understand that using the locking date for example.

Then for any asset, when the depreciation board will be computed all lines will be flagged 'init' until this date

**Comment by luc-demeyer** [comment]
I think we could as well re-use the 'fiscalyear_lock_date' in stead of yet another date field and document in the account_asset _management README.rst that this parameter is used for this operation (which is a one time operation for a customer who starts to use this module).

**Comment by fclementic2c** [comment]
Ok it's your baby :)

go for using the fiscalyear_lock_date
