### ISSUE TITLE
[11] Change Menu

### ISSUE THREAD

**Issue by arveitch** [OCA/account-financial-tools#734]
For the menuitem in account_move_view.xml I think it would be better to change:

    parent="account.menu_finance_entries"

To:

    parent="account.menu_finance_entries_accounting_entries"

This is a more logical place for it to be.

**Comment by pedrobaeza** [comment]
Which module? Screenshots, please?

**Comment by arveitch** [comment]
The module is Account Reversal. I have moved 'Journal Entries to be Reversed' from being at the bottom of the menu, under Lock Dates, to the section that deals with Accounting Entries.

<img width="289" alt="menu" src="https://user-images.githubusercontent.com/7735894/48832245-a1b65000-ed70-11e8-9f05-e2df6ae438c8.png">

**Comment by pedrobaeza** [comment]
OK, good idea. Please do a PR changing that.

**Comment by bodedra** [comment]
We can close these in favor of https://github.com/OCA/account-financial-tools/pull/747
