### ISSUE TITLE
[12.0] account_invoicing is gone what happens with modules that depend on this?

### ISSUE THREAD

**Issue by icf20** [OCA/account-financial-tools#759]
is there any way to replace account_invoicing in the short term?

**Comment by pedrobaeza** [comment]
This question should be done on forums.

**Comment by icf20** [comment]
@pedrobaeza i would if oca forums have fixed this issue https://github.com/odoo/odoo/issues/23527

**Comment by pedrobaeza** [comment]
This is not something of OCA.

**Comment by icf20** [comment]
afaik account_check_deposit module requires odoo SA account_invoicing
