### ISSUE TITLE
[currency_rate_update] Admin.ch service doesn't work

### ISSUE THREAD

**Issue by ecino** [OCA/account-financial-tools#766]
When trying to use service admin.ch to update the currencies with the module `currency_rate_update`, we get an xml error because the service seems broken.

The url of the server looks to be : http://www.afd.admin.ch/publicdb/newdb/mwst_kurse/wechselkurse.php

But this page returns "Res empty" instead of an expected XML.

Maybe the url needs to be updated? By looking on the website, it looks like this is a valid URL:
http://www.pwebapps.ezv.admin.ch/apps/rates/rate/getxml?activeSearchType=today

**Comment by Drsmartinkus** [comment]
@ecino it seems that url has changed again fix on https://github.com/OCA/account-financial-tools/pull/1310
