### ISSUE TITLE
Journal Entry's Source Document

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-tools#788]
Our accountant have problem knowing which Journal Entry created from which front document. (I know there is text reference field, but that is not what we need as text is always changeable)

We want to have a field **document_id** as field.Reference() (invoice, payment, hr.expense) may be as computed stored field in **account.move** that can link back to the front document who creates it.

This feature sound reasonable to be here? Any similar feature else where? Thanks

**Comment by dominiquekonsuntack** [comment]
To have more information as for where the journal entry comes from: yes

To make it a many2one to a model.. not really. Journal entries can be
created by invoice, payment, reconciliation voucher, stock move, payslip,
asset depreciation, reversal entries etc..

May be a hidden field to hold the name of the original model, and then a
search button? In other words nothing that would be automatically
calculated.

My two cents..

**Comment by kittiu** [comment]
@dominiquekonsuntack that's why I like to propose using Reference field which hold both model and res_id, i.e., "account.invoice,1". This is many2one field. Only reference field can hold multiple type of objects.

**Comment by kittiu** [comment]
Hi, I just make PR for this. Another main reason I think we need this kind of perm link is all about reporting. Many account reports from account.move.line require source document + its related (orm) info.
https://github.com/OCA/account-financial-tools/pull/790
Currently, we did for only invoice/payment and expense just to proof concept. In longer term, we can create more small modules for each new document type
