### ISSUE TITLE
[v11] account_partner_required nothing happend

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-tools#810]
hi i am using odoo v11 i install account_partner _required i change the policy of account to never but i can write the partner in account move not disable i try in runbot and not work also  
thanks @sbidoul @pedrobaeza

**Comment by lili94** [comment]
can anyone help please @sbidoul

**Comment by lili94** [comment]
@pedrobaeza  do you have some suggest please

**Comment by sbidoul** [comment]
@lili94 I've never used this module on v11. A quick look at the code shows nothing suspicious.

**Comment by lili94** [comment]
@sbidoul  i need to disable a partner for some account in move line any suggest
