### ISSUE TITLE
[7.0] account_move_line_search_extension : impossible to post a manual entry

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-financial-tools#82]
module : account_move_line_search_extension (with filters on top of the tree view 'journal items'
- select a journal and type in a period
- click on create 
- input a date, description, debit... and press enter
  -> the new line generate is considered a new move so it is impossible to create the couterpart entry of the first move

I noticed a second issue : After you select the journal and period and click on create, the journal field on the move line is not automatically field in + the 2 columns journal and period are not automatically hidden as in standard.

**Comment by fclementic2c** [comment]
@luc-demeyer Hi luc, I just notice a problem with this module that I report here. If you have some time to check it out

**Comment by luc-demeyer** [comment]
Frédéric,

The purpose of this module is easy consultation (drill down), not the (rather unusable) ‘fast encoding’ mechanism which is provided via the standard ‘Journal Items’ menu entry.

What I propose in order to fix the issue reported by you is to disable the creation of new entries from the ‘Journal Items Search All’ list view.

Do you  agree with this or do you have other suggestions ? 

Tx,

Luc

 http://www.noviat.com/ www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by pedrobaeza** [comment]
I also agree with the solution. This must be readonly.

**Comment by fclementic2c** [comment]
Now I understand why you did not want to merge both menus 'journal items' and 'journal items search all'... but now both menus are merged :(https://github.com/OCA/account-financial-tools/commit/78205e0ee4f295b77598c3b72f3766e44cf1bed8)

Ok we will propose a PR to revert this but as you say, we also need to hide this create button if possible.

Functionnaly, we absolutely need to post entries from 'journal items' because it is much faster than creating move from 'journal entries' (ie : automatic VAT) when it comes to post petty cash or the corporate credit card expenses for ex.

**Comment by pedrobaeza** [comment]
But what I don't understand is that if you can fast-encoding journal entries with the other menu, why you cannot do it in this new menu. Same mechanisms can be provided on both.

**Comment by luc-demeyer** [comment]
@pedrobaeza the so-called "fast" encoding uses the period selected in the standard 'Journal Items' menu whereas the 'search all' allows partial period names (e.g. to search on all items in periods with 2014 in the name). Merging both approaches will be confusing for the end user, hence my proposal to keep the two menu items and block creation of journal items when using the 'search all'.

**Comment by pedrobaeza** [comment]
@luc-demeyer Understood

Let's keep both menus and we should add this clarifications on module description to avoid this debate occurs again in the future. Don't you think?

**Comment by StefanRijnhart** [comment]
Closing as proposed workaround was merged.
