### ISSUE TITLE
[10.0][account_balance_reporting] Ordenación Inadecuada.

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/account-financial-tools#836]
El balence de sumas y saldos OCA, no se ordena por cuentas o grupos de cuentas que es lo que los gestores y contables necesitan.

No se cual es la ordenación actual, pero incluso no creo que sea por descripción.

Este es un ejemplo.

![imagen](https://user-images.githubusercontent.com/18347857/58702470-33e58380-83a6-11e9-8c9f-97ef4da4524e.png)

**Comment by pedrobaeza** [comment]
Proper repository is OCA/account-financial-reporting, and it should be in English, but I give you a hint about the problem: accounts don't have an account group assigned.

**Comment by pedroortega-punt** [comment]
I think it is not correct, the accounts have all their group assigned.

![imagen](https://user-images.githubusercontent.com/18347857/58747848-0d404f00-8471-11e9-9575-824f44edc9d5.png)

**Comment by pedrobaeza** [comment]
Write to OCA/account-financial-reporting reproducing the problem in runbot.
