### ISSUE TITLE
Asset with analytical (not asset category)

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/account-financial-tools#845]
Is there any way to assign an analytic account to an asset? No to an asset category.
Thanks.

**Comment by pedrobaeza** [comment]
With which asset module?

**Comment by pedrobaeza** [comment]
Which Odoo version?

**Comment by pepitovadecurt** [comment]
Sorry, ODOO 10 Comunity and the module "account_asset" version 10.0.1.0

**Comment by pedrobaeza** [comment]
https://github.com/OCA/account-analytic/tree/10.0/account_asset_analytic

**Comment by pepitovadecurt** [comment]
It was just that I need! 
Still getting acquainted with Github (also with Odoo)
Thanks
