### ISSUE TITLE
[V12.0] account_chart_update taxes with children

### ISSUE THREAD

**Issue by fdiaz-LPA** [OCA/account-financial-tools#848]
Hello,
I am having an issue when updating taxes where a new record in xml is a group.
Odoo won't show any errors, the updating windows after last step just waits until timeout is reached.
All steps until you lunch the process are ok

To try it I faked a duplicated the record of "IVA 21% Adquisición Intracomunitaria. Bienes corrientes" in the xml file "account_tax_data.xml of the l10n_es". Then I updated the Module and lunched the chart update process. The new record will not be created after a long wait, no errors are shown

Regards

**Comment by pedrobaeza** [comment]
I haven't got any problem with that, as Spanish chart of accounts has taxes with groups. Unless you show some logs on infinite recursion or check if you have any kind of lock, we can't test and "solve" this.

**Comment by fdiaz-LPA** [comment]
Hello @pedrobaeza, there are not problems with Spanish Charts, I mentioned it as example.
The problem may be with the module account_chart_update when you load an xml with child taxes

**Comment by pedrobaeza** [comment]
Yes, but this still doesn't seem a valid issue, as duplicating that data is a trick for doing things fail and not a real condition.

**Comment by fdiaz-LPA** [comment]
Hello @pedrobaeza 
I have not any king of interest of faking a fail or similar. I just found an abnormal behaviour and I comment it in case somebody else comes across the same situation.

If there is not issues, fear enough with me!!!

I will start assuming  that I am wrong. If a chart template suffers changes and it is updated in an Odoo instance, you can use the module account_chart_update so that your current charts, taxes and/or fiscal positions that you are using can take those changes from the updated template.

As I was playing around, I found the situation where, when you create a new tax in a chart template and this new tax is a child tax, when you run through the account_chart_update process, the child tax does not get created and no errors are thrown.

To be more explicit, when I mentioned (I faked a duplicated), I meant I reused the record I copied -> pasted -> modified to create a new child tax. A duplicated record will give you an error when you update the module

- Original tax : "IVA 21% Adquisición Intracomunitaria. Bienes corrientes"

`    <record id="account_tax_template_p_iva21_ic_bc" model="account.tax.template">
        <field name="description">P_IVA21_IC_BC</field>
        <field name="amount_type">group</field>
        <field name="amount" eval="100"/>
        <field name="children_tax_ids" eval="[(6, 0, [ref('account_tax_template_p_iva21_ic_bc_1'), ref('account_tax_template_p_iva21_ic_bc_2')])]"/>
        <field name="chart_template_id" ref="l10n_es.account_chart_template_common"/>
        <field name="type_tax_use">purchase</field>
        <field name="name">IVA 21% Adquisición Intracomunitaria. Bienes corrientes</field>
        <field name="tax_group_id" ref="tax_group_iva_21"/>
    </record>`

- Duplicated and modified TAX for testing:

`    <record id="account_tax_template_p_iva21_ic_bc9" model="account.tax.template">
        <field name="description">P_IVA21_IC_BC9</field>
        <field name="amount_type">group</field>
        <field name="amount" eval="90"/>
        <field name="children_tax_ids" eval="[(6, 0, [ref('account_tax_template_p_iva21_ic_bc_1'), ref('account_tax_template_p_iva21_ic_bc_2')])]"/>
        <field name="chart_template_id" ref="l10n_es.account_chart_template_common"/>
        <field name="type_tax_use">purchase</field>
        <field name="name">IVA 9 21% Adquisición Intracomunitaria. Bienes corrientes</field>
        <field name="tax_group_id" ref="tax_group_iva_21"/>
    </record>`

I used this method as it a simple way for anyone to test, modify your existing chart template, update module and run the account_chart_update process

In any case, thank you very much for your comments and help.

I will close this not issue.
Regards
Francisco Díaz

**Comment by pedrobaeza** [comment]
I'm not saying you are faking anything, but we should be also pragmatic: if there's no reproducible case in any localization dataset, then we shouldn't care about this. It would be different if you are providing directly a pull request with the solution. Reviewing, approving and merging that patch is less effort and it's admissible. What I'm not going to do is to patch this hypothetical case, investing a lot of time. Any way, you can leave this issue opened as "documentation" for the future if you prefer.

**Comment by fdiaz-LPA** [comment]
I am not a skilled developer, I am more of an integrator. I am not skilled enough to detect where the problem may arise, I promise I tried.

If I manage to get skilled, in long term if ever, my goal would be to add all the taxation for The Canary Island to OCA localization and OCA Spain, as it is mentioned [Here](https://github.com/OCA/l10n-spain/issues/1008)

I do not want to give false expectations as it may long time, so that I will be skilled enough, to commit to such responsibility.

I locally cloned [this repo](https://github.com/sistemasdedatos/odoo-addons/tree/12.0/l10n_es_igic) and I managed to adjust all accounts and taxes. I got blocked when child taxes were not loaded. Just to verify that It was not a problem with the modified loaded xml data, I tried by adding a new child tax to the Spanish Tax Template.

I agree with you "Reviewing, approving and merging..." whenever I am ready to do it, I will!!!

**Comment by pedrocs-exo** [comment]
Hi,

I can confirm this bug in V12 (and a nasty one BTW!). Children tax updates are ok, but their parent never gets created and hangs the system.

It's quite simple to reproduce. Just add the following XML chunk to the spanish localization account_tax_data.xml (its a simple copy of a tax set):

>     <record id="account_tax_template_p_iva21_sp_in_1x" model="account.tax.template">
>         <field name="description">P_IVA21_SP_IN_1x</field>
>         <field name="type_tax_use">purchase</field>
>         <field name="account_id" ref="l10n_es.account_common_477"/>
>         <field name="sequence" eval="10"/>
>         <field name="name">IVA 21% Inversión del sujeto pasivo intracomunitariox (1)</field>
>         <field name="refund_account_id" ref="l10n_es.account_common_477"/>
>         <field name="chart_template_id" ref="l10n_es.account_chart_template_common"/>
>         <field name="amount" eval="-21"/>
>         <field name="amount_type">percent</field>
>         <field name="tax_group_id" ref="tax_group_iva_21"/>
>         <field name="tag_ids" eval="[(6, False, [ref('mod_303_10_11'), ref('mod_303_14_15_purchase')])]"/>
>     </record>
>     <record id="account_tax_template_p_iva21_sp_in_2x" model="account.tax.template">
>         <field name="description">P_IVA21_SP_IN_2x</field>
>         <field name="type_tax_use">purchase</field>
>         <field name="account_id" ref="l10n_es.account_common_472"/>
>         <field name="sequence" eval="20"/>
>         <field name="name">IVA 21% Inversión del sujeto pasivo intracomunitariox (2)</field>
>         <field name="refund_account_id" ref="l10n_es.account_common_472"/>
>         <field name="chart_template_id" ref="l10n_es.account_chart_template_common"/>
>         <field name="amount" eval="21"/>
>         <field name="amount_type">percent</field>
>         <field name="tax_group_id" ref="tax_group_iva_21"/>
>         <field name="tag_ids" eval="[(6, False, [ref('mod_303_36_37'), ref('mod_303_40_41')])]"/>
>     </record>
>     <record id="account_tax_template_p_iva21_sp_inx" model="account.tax.template">
>         <field name="name">IVA 21% Adquisición de servicios intracomunitariosx</field>
>         <field name="description">P_IVA21_SP_INx</field>
>         <field name="type_tax_use">purchase</field>
>         <field name="chart_template_id" ref="l10n_es.account_chart_template_common"/>
>         <field name="amount_type">group</field>
>         <field name="amount" eval="100"/>
>         <field name="children_tax_ids" eval="[(6, 0, [ref('account_tax_template_p_iva21_sp_in_1x'), ref('account_tax_template_p_iva21_sp_in_2x')])]"/>
>         <field name="tag_ids" eval="[(6, False, [ref('mod_303_10_11'), ref('mod_303_14_15_purchase'), ref('mod_303_36_37'), ref('mod_303_40_41')])]"/>
>         <field name="tax_group_id" ref="tax_group_iva_21"/>
>     </record>

and then try to update the chart of account taxes. The log will display

> Created tax 'IVA 21% Inversión del sujeto pasivo intracomunitariox (1)
> Created tax 'IVA 21% Inversión del sujeto pasivo intracomunitariox (2)

and then a glorious silent hang shows up.

I can try to help if the maintainers so wish.

**Comment by pedrobaeza** [comment]
If you provide a pull request fixing the problem, then I'll review it.

**Comment by pedrobaeza** [comment]
This was fixed in a696148b4cb6e397ee0c0929a715f9a8cf26ff8a and e2750be00bef033c2971534c2139fff79dcb9523
