### ISSUE TITLE
[12.0] account_asset_management: Fiscal year mustn't be mandatory

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#850]
On a regular 12.0 installation, you don't need to create fiscal years for doing regular accounting. If that happens, considered fiscal year is the natural year.

But with this module, you are forced to create fiscal years although using natural ones.

**Comment by luc-demeyer** [comment]
A small change that we could implement easily if we have sufficient support for it by the OCA accounting specialists.

**Comment by pedrobaeza** [comment]
Which kind of support do you need?

**Comment by mmotahar** [comment]
As mentioned in #918 by running functional tests using various localisation packages that have fiscal year other than the European ones, We found that the module does not work if the fiscal year is NOT from 1st Jan to 31 December. details are added here #918

**Comment by pedrobaeza** [comment]
This was fixed in #870
