### ISSUE TITLE
[10.0] account_check_deposit: can't reconcile bank statement line with check deposit

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/account-financial-tools#853]
After posting a check deposit, one would expect to be able to reconcile it with a bank statement line. But that can't be done because the deposit move doesn't appear in the possible reconcilable  items.

To reproduce the problem just follow the instructions on the Configurations and Usage sections of the README file, keeping the default values (Check Deposit Offsetting Account = Bank Account). Then, create a bank statement with a line having the same date and value of check deposit and hit Reconcile. The check deposit move will not appear.

**Comment by alexis-via** [comment]
You can use this patch on odoo to fix it : https://github.com/akretion/odoo-usability/blob/10.0/account_usability/account_several_improvements.diff  (it's the 1st change of the diff which solves the pb)
or use OCB, cf https://github.com/OCA/OCB/blob/10.0/addons/account/models/account_bank_statement.py#L569
