### ISSUE TITLE
Module that facilitates the encoding of losses on your customers' receivables

### ISSUE THREAD

**Issue by gva-acsone** [OCA/account-financial-tools#856]
Hello everyone,

Has anyone heard of a module that _facilitates the encoding of losses on your customers' receivables_? The idea is to avoid creating a manual journal entry every time you need to register a loss when you know your customer will never pay your invoice.

It doesn't look like such a module already exists in the community, so we plan to develop a new module to add this functionality. It would work as follows:

A wizard (available in 'Action') can be opened from the list view and/or the form view of customer invoices. Hence, several invoices can be selected at once.

In this wizard, three fields need to be filled in (some parameters can be defined on the company to pre-fill these fields automatically):

1. Account that will be used to register the loss
2. Accounting date
3. Journal

When the user confirms, a journal entry to register the loss is created for each of the selected invoices:
This journal entry is a reverse of the journal entry linked to you invoice, except for the 'income account' that is replaced by the 'loss' account encoded in the wizard.

Moreover, this 'loss' journal entry will be reconciled with the customer invoice to mark it as 'paid'.

Any comments, remarks, questions about this module? Or a link to an existing module that works similarly?

Thank you very much for your feedback,

Cheers,

Guillaume

**Comment by sbidoul** [comment]
> except for the 'income account' that is replaced by the 'loss' account encoded in the wizard.

income account*s*, plural since there is potentially more than one income line on the invoice

> Moreover, this 'loss' journal entry will be reconciled with the customer invoice to mark it as 'paid'.

By the regular reconcile feature of account_reversal.

Do we need to do something special with partially paid invoices, and credit notes?
