### ISSUE TITLE
[RFC] merging all account_***_menu into a single module

### ISSUE THREAD

**Issue by legalsylvain** [OCA/account-financial-tools#857]
Hi all, 
Since new versions of odoo, some menus / actions in accounting part are not available.
For that purpose, some modules exist like in V12 : 
- account_group_menu
- account_tag_menu
- account_type_menu
- account_coa_menu ([Pending PR](https://github.com/OCA/account-financial-tools/pull/855), review welcome, BTW ;-) )

I see all that modules rather boring to maintain.

I so propose to merge all that modules, in a single one, name ``account_menu`` or ``account_extra_menu`` (or whatever) for the next version V13.

The objective of such module would be "_To provide all actions and menus related to all the models introduced by the ``account`` module_".

I think that such design should be extended for all Core modules, if menus or action are missing in other odoo modules.

What to you think about ? 

CC : reviewer of the various modules : @rven, @tbaden, @pedrobaeza, @pniederlag, @ThomasBinsfeld, @benwillig,@mpanarin

**Comment by pedrobaeza** [comment]
Let's see what happen in v13 with the accounting refactoring first, but I agree on principle.

**Comment by arthru** [comment]
It would be really convenient to have a single account_menu 

Maybe just start by creating an account_menu with all account_*_menu as dependency ?

**Comment by legalsylvain** [comment]
> Maybe just start by creating an account_menu with all account_*_menu as dependency ?

:+1: Good idea. I'll integrate it in this PR : https://github.com/OCA/account-financial-tools/pull/855
