### ISSUE TITLE
account_check_deposit : Use for Cash Deposit to Bank

### ISSUE THREAD

**Issue by mslokhat** [OCA/account-financial-tools#863]
Hi,
Is there any option to transfer Cash payment to Bank account?

Process is usual like that : 
Accountant receive payment in form of Cash or Check . 
each next day, all cash and checks are sent to bank and a Remittance is delivered by the bank
Bank account is then credited with all Checks and Cash

Thanks

**Comment by kittiu** [comment]
Hi, I am not 100% sure this is what you want. But I see it as enhancement to account_check_deposit to accept partial/full move from cash/check (intransit) being paid (in payment document) to bank account.
https://github.com/Saran440/account-financial-tools/tree/12.0-add-account_payment_intransit/account_payment_intransit

**Comment by mslokhat** [comment]
Hi,
Thank you. i will have a look
Rgds
