### ISSUE TITLE
[12.0] account_asset_management: Inconsistencies on method_time values

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#877]
While analyzing the code for migrating `l10n_es_account_asset`, I see some inconsistencies in the module for the multiple `method_time` values:

* Main module is supposed to only support computation by years, but at the end, there's lot of code here mentioning the other methods.
* Why doing different depreciation computations depending on `method_time`? For me, important things are depreciation starting date, and depreciation stop date. The rest of the computations must be the same depending on these 2 data. In fact, in `l10n_es_account_asset`, I have needed to compute properly stop date:

  https://github.com/OCA/l10n-spain/pull/1166/files#diff-b2f263a1a1799d31829a83fea1626d32R59

  and then simulate that this is depreciation by years:

  https://github.com/OCA/l10n-spain/pull/1166/files#diff-b2f263a1a1799d31829a83fea1626d32R111

* For `method_time` = 'end' or 'number', only linear depreciation is allowed. Why? You can have a regressive computation while specifying a number of depreciations. Doing what I say on second point you will have it properly.
* If so, there's not too much sense on splitting the module in 2, but well, if so, the second one will be very light (the same as `l10n_es_account_asset` if we do it).

I can work on this if you think it's interesting. I can also extract this on an issue if you prefer.

**Comment by luc-demeyer** [comment]
I had a look into account_asset OE 12.0, this one also still contains the methods 'number' and 'end', hence we could indeed merge the 'account_asset_management_method_number_end' into the main module.

I my own customer base (including a customer with a subsidiary in Spain) I never encountered the need for the 'end' and 'number' methods. I have deployed these time methods several times for revenue/cost spreading and for that purpose linear depreciation is ok.

Is this urgent or can it wait until the upcoming OCA code sprint ?
We'll need to refactor the computation logic.I think would be better if we first align the approach with several users of this module before we start to work on the code.

**Comment by pedrobaeza** [comment]
Well, I have several customers about to migrate that use that methods, but I can take care of the needed changes.
