### ISSUE TITLE
[11.0,12.0][account_asset_management] Recalculating depreciation schedules

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-tools#897]
Hi,

It is often necessary to incorporate capital improvement cost information for an asset (for example, after some years after the initial start of the asset you have made a repair to the asset that has increased it's value), or to otherwise revise an existing depreciation schedule (for example, after some years the asset has degraded and you decide to reduce the number of years of the life of the asset), you need recalculate the depreciation schedule.

Currently there seems to be no option to recalculate the depreciation schedule.

In my opinion the user should be able to change the depreciation base, time method, number of years, computation method, of the asset... at any time, and the system would recompute the Depreciation Board, accepting all the already posted (or forced initial) depreciation lines and adding as many lines as needed afterwards.

Example:

An asset starts in 01/01/2000, with a value of 3000€ and a linear depreciation over 5 years. 

![image](https://user-images.githubusercontent.com/7683926/66801527-aac88680-ef19-11e9-8cb8-9daaf01001b0.png)

In 01/01/2004 the residual value is 1200€. The company then performs a significant repair operation, that results in an increase of the asset value of +2000€.

At this point the user should be able to change the purchase value from 3000€ to 5000€ and recalculate the depreciation board starting from this date. In this case, since the number of years would not be enough to completely amortize the asset, one would need to extend the years in order to make sure the value is reduced to the minimum.

See https://www.ibm.com/support/knowledgecenter/en/SS5RRF_7.6.7/com.ibm.trn.doc/plustasset/c_recalc_dep_sched.html

cc @luc-demeyer @pedrobaeza @etobella

**Comment by kittiu** [comment]
Hello @jbeficent 
cc @wipawii

I do agree that asset management is important and need to be more flexible than this.

Question: when you do the repair operations, and want that expense to be included in the asset (beside the recalc depre table), you will need to have another set of account moves that add value from expense to asset too, correct? When you say "change the depreciation base", will journal entry created to adjust asset value?

I am interested in flexible depre table, but also other kind of operation before it (to create adjustment journal to link to the asset), the most cases I need are,
- Asset Adjustment (to itself)
  - Change asset category, i.e., when first selection of category is not correct.
  - Change the analytic account of asset owner,
  - Change of based value based on any expenses, i.e., repair operation as in your case.
- Asset Transfer (to other)
  - Merge, i,e.., bought 2 asset as WIP. Then, merge them into 1 final asset.
  - Split, i.e., bought a big asset, then split them into multiple small asset.

WDYT?

**Comment by JordiBForgeFlow** [comment]
@kittiu We have been thinking about this.

In our opinion this would require a major refactoring with respect to the current code.

First, the asset depreciation table should take into account all the account.move.line associated to asset valuation changes. That way, you could, for example:

1) Do a repair and allocate directly the expenses to a given asset.
2) Purchase new material or services that you want to allocate to an existing asset.

With respect to merging assets, as far as I understand this would mean totally depreciating the 2 assets in WIP and then creating a new asset with the sum of the remaining valuation of the two.

With regards to splitting, I guess that it would be similar to merging. First end the big one and inmediately create the smaller ones.  But it's not simple...
