### ISSUE TITLE
[account_asset_management] Calculate depreciation for each period based on the number of days in the period

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-tools#899]
An asset with purchase value of 1200 which is going to depreciation over 1 year with monthy depreciations, now depreciates 100 each month.

But we want the depreciation schedule to be based the actual number of days in each month. In February, depreciation will be approximately 92, while in March depreciation will be approximately 102 - there are 3 days more in March than there are in February.

Based on what I've seen in the code, this would require a significant refactoring.

cc @joansis @etobella @luc-demeyer @kittiu

**Comment by kittiu** [comment]
@jbeficent you mean calculate by days instead of by period? We dit it, and I think @luc-demeyer is about to merge https://github.com/OCA/account-financial-tools/pull/852

**Comment by JordiBForgeFlow** [comment]
Thanks @kittiu. That's what I was looking for!
