### ISSUE TITLE
[RFC] - account_asset_management_method_number_end usage

### ISSUE THREAD

**Issue by sbejaoui** [OCA/account-financial-tools#922]
Hi guys,

I need your help to understand some implementation details in `account_asset_management`.

In many places in the code, I see a business logic based on different values of the field `method_time` [(example)](https://github.com/OCA/account-financial-tools/blob/10.0/account_asset_management/models/account_asset.py#L264) but this filed have one possible [choice](https://github.com/OCA/account-financial-tools/blob/1ebbdd975c89288ad286938553f794cebf5b1b8e/account_asset_management/models/account_asset_profile.py#L139).

I see that in V10, there was this module [account_asset_management_method_number_end](https://github.com/OCA/account-financial-tools/tree/10.0/account_asset_management_method_number_end) that simply add the extra values of the `method_time` field.

- Why this values are not in the base module?
- Or why the logic linked to this values is not totally in `account_asset_management_method_number_end` module

cc/ @sbidoul , @chrisdec

**Comment by pedrobaeza** [comment]
See #877 for similar analysis
