### ISSUE TITLE
Travis failing in 12.0

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/account-financial-tools#947]
Travis is not working for 12.0 branch

![image](https://user-images.githubusercontent.com/1914185/76633258-bcec3680-6544-11ea-83d9-5703f6555de4.png)

![image](https://user-images.githubusercontent.com/1914185/76633220-ae058400-6544-11ea-94ed-81a4e779e9ef.png)

And apparently there's an error on `account_check_deposit` tests, but I don't know since when, because builds where giving false greens

This is from translation job: https://travis-ci.org/github/OCA/account-financial-tools/jobs/658704758
![image](https://user-images.githubusercontent.com/1914185/76633386-e7d68a80-6544-11ea-84e4-d32f739e1c3b.png)

**Comment by AaronHForgeFlow** [comment]
All merge attempts in 12.0 have failed for this reason. I am not too familiar to that module. @legalsylvain I see you are improving this module here https://github.com/OCA/account-financial-tools/pull/872 Could you point us into the right direction in order to fix this? Thanks

**Comment by pedrobaeza** [comment]
This has been fixed in #950

**Comment by pedrobaeza** [comment]
FYI it seems a default changed in Odoo core.
