### ISSUE TITLE
Branch 13.0 is merged wrongly, how to revert back before further commit.

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-tools#963]
@OCA/accounting-maintainers 
We have situation here, https://github.com/OCA/account-financial-tools/pull/956
When this happen, is it correct to revert to 7 Apr, 2020 and then git push -f ?

**Comment by AaronHForgeFlow** [comment]
I think a new PR that revert the changes is always better than git push -f. Could you create a PR reverting the changes?

**Comment by kittiu** [comment]
@AaronHForgeFlow thanks again for your advice, I think you mean this? git revert xxx...HEAD
https://github.com/OCA/account-financial-tools/pull/965
Please help merge if you think it looks ok. :)
