### ISSUE TITLE
[IMP][account_asset_management] Depreciation board computation upon asset confirmation

### ISSUE THREAD

**Issue by qgroulard** [OCA/account-financial-tools#967]
Hello,

I was wondering if there is any good reason why de depreciation board is not auto computed when the asset is confirmed ?

The less clicks the happier our customers are. :smiley:

**Comment by pedrobaeza** [comment]
The only reason I see for that is for preventing the recomputation if you go back to draft and re-confirm.

@luc-demeyer is there any special reason?

**Comment by luc-demeyer** [comment]
The recomputation is not done to allow manual changes to the depreciation table to adjust the computation (in case of computation errors or if the customer wants other roundings e.g to align with computation done by the accounting package of this external accounting agency, ...).

I have observed in the past several cases where computation is not fully correct (and there are still open issues e.g. https://github.com/OCA/account-financial-tools/issues/918).

And we don't cover yet all asset computation algorithms (e.g. usage based in case of manufacturing) hence we need to be able to enter tables manually and NOT recompute automatically when confirming.

Now I agree that this is a bit tricky and error prone.
An option could be to add a boolean on the depreciation ("autocompute") which we set by default but can be turned off in case of a manually uploaded/entered table.

**Comment by pedrobaeza** [comment]
I think it's better to simply recompute the table automatically if no manual entries found (`depreciation_line_ids` empty or similar).

**Comment by luc-demeyer** [comment]
@pedrobaeza 
I agree that in case of empty depreciation_line_ids we should recompute.
I can make a PR for that (for 13.0)

**Comment by qgroulard** [comment]
I open a PR for 12.0: https://github.com/OCA/account-financial-tools/pull/973

Could you please check that it's done right ? Thank you.

**Comment by pedrobaeza** [comment]
Closing this as there's a PR for continuing there.
