### ISSUE TITLE
Overlapping between account_lock_to_date and account_lock_date_update?

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-tools#968]
It seems both modules are equal.

@JordiBForgeFlow @AaronHForgeFlow yours seems to arrive later. Is there any difference with the other?

**Comment by enricostano** [comment]
I've been struggling with this duplicity and I'm still not sure which one I should use.

Do we have any plan to merge them into one module?

Thanks for the hard work in any case!

**Comment by AaronHForgeFlow** [comment]
Hi all,

They are not the same at all,
account_lock_to_date allows to restrict to post account moves **in the future**.

account_lock_date_update allows to modify the standard lock dates, that restrict to post account moves **in the past**.

Regards

**Comment by enricostano** [comment]
@AaronHForgeFlow thanks for clarifying!

So, if I'm in **2021** and I don't want to let people create account moves in **2020** I need to install `account_lock_date_update`. Right?

**Comment by AaronHForgeFlow** [comment]
Hi @enricostano . Yes, in that case you need account_lock_date_update module. That feature is a standard feature, but without the OCA module there is no way a user can change the date fields, and that is why that module is needed.
