### ISSUE TITLE
[12, 13][IMP] account_spread_cost_revenue, auto create spread table by product

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-tools#992]
cc @astirpe @CasVissers 

In my project, I have a requirement to, when validate invoice, auto create spread table.
And so, what I did is to link the Spread Template with product.

![Selection_066](https://user-images.githubusercontent.com/1973598/82111050-477f2b00-976c-11ea-8251-e4ae1215ad08.png)

If this product is selected on invoice, validating it will create spread table based on template right away.

I think this feature is easy to do and not break existing feature, so I like to propose a PR.

WDYT?

**Comment by CasVissers-360ERP** [comment]
Nice feature, think it can be added without breaking existing features!

Don't like the intrusive view update on the product form view. I would prefer a more minimalistic approach on the accounting page. Maybe just adding the template field with some domains based on can be purchased / can be sold.

I also see a "spread over" field?

**Comment by kittiu** [comment]
@CasVissers 
Good idea on not being intrusive on product. But I think by link it to account may not cover all case. Even with same account some time we want auto spread but sometime we don't. I think we can cover all possible case by both! Let me think.

I am thinking to add the link to products and/or accounts in the template window itself. It can be minimal as option. WDYT?

Spread over is about the spread start and end date. What I show is based in my case which want to use contract date, please ignore it. The OCA one will be more generic.

**Comment by kittiu** [comment]
![Selection_068](https://user-images.githubusercontent.com/1973598/82138817-85a04b80-984d-11ea-8af5-0c0716ecc5b3.png)

**Comment by kittiu** [comment]
Let's continue here,
https://github.com/OCA/account-financial-tools/pull/993

**Comment by astirpe** [comment]
> Spread over is about the spread start and end date. What I show is based in my case which want to use contract date, please ignore it. The OCA one will be more generic.

@kittiu are you aware of module [account_spread_contract](https://github.com/OCA/account-financial-tools/pull/737 )?

**Comment by kittiu** [comment]
@astirpe no, I am not aware of that. May I summarize for further discuss.

**account_spread_contract**
- Define the `spread_template_id` in account.analytic.invoice.line,
- Use the spread_template_id to create spread table during invoice creation (not during validation).
- No config in Spread Template window, (do config in analytic)

**https://github.com/OCA/account-financial-tools/pull/993**
- Config in Spread Template, for the possible matching invoice line with product/account
- Use it to create spread table during invoice validation

I think both module do not duplicate feature yet, because one is for analytic and another is for product/account.

However, after thinking, if you don't mind, I think I can add Analytic as another criteria, and it should work for case of Contract too (is it?)

![Selection_075](https://user-images.githubusercontent.com/1973598/82301150-07c17900-99e2-11ea-9b8f-f6bdea71875e.png)

Note: I like the comment of @CasVissers about not being intrusive. So I think, by centralize all auto spread creation in the Spread Template make good sense?

WDYT?

**Comment by kittiu** [comment]
@astirpe any further comment?

**Comment by kittiu** [comment]
Analytic as criteria added.
https://github.com/OCA/account-financial-tools/compare/5bf2a16e0cc7eb7a2e762ada0a0ec2126d7232bf..626d4c70460ee9ca2d90320aaa50b8bb3dfb69d7
